### ISSUE TITLE
WSDL support

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apimanager-swagger-promote#10]
When the tool really becomes a API-Manager CLI, meaning support more than only importing Swagger-Based APIs, we can consider WSDL-Support as well.

**Comment by rchinthakuntla** [comment]
I agree. Day by day, the need for supporting WSDLs in API Manager is dampening. Nice to have feature but not a priority. We might instead want to consider supporting RAML. Mulesoft is still not giving up on promoting RAML.

**Comment by gcornacchia** [comment]
I'm interested in this feature because in the organizations I work for SOAP services are widely adopted as internal standard.
