### ISSUE TITLE
cannot build mvn project

### ISSUE THREAD

**Issue by vuvdoan** [Axway-API-Management-Plus/apimanager-swagger-promote#103]
Hi @cwiechmann,

I cannot build the project due to missing parent dependencies in the modules.

`[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.github.axway-api-management-plus.swagger-promote:distribution:[unknown-version]: Could not find artifact com.github.axway-api-management-plus.swagger-promote:axway-swagger-promote:pom:1.6-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]`

Is there any reason you don't use relativePath for the parent? If I remember correctly it was that way in the past, but changed in release 1.5.3.

Thanks
Vu

**Comment by cwiechmann** [comment]
Can you perhaps share the complete the pom.xml you are using in your project? I tried to reproduce the issue, but it seems to work okay.

**Comment by cwiechmann** [comment]
@vuvdoan, it was at least not intentional to change something around the parent pom. Perhaps I'm not following the Best-Practice for that. 😕 Any advice is highly welcomed.

**Comment by vuvdoan** [comment]
I'ts actually your project :)  I just cloned it and run mvn (develop branch).  No maven settings was specified. So mvn should look up for dependencies in maven central repository. My colleague also tried but has the same problem.  Can you delete  the  com/git/axway-apimanagement-plus artifact in your local maven repository and try again?

**Comment by cwiechmann** [comment]
Got you! Just fixed it by re-adding the relativePath. Now it should work on your side as well. Thanks for letting me know.

BTW: I know you are working on a Maven-Plugin. If you believe some changes in the Core-Code would help you to integrate the Swagger-Promote-Lib better (more easy), just let me know. Or create a Pull-Request. 
As I haven't started to work on a Maven-Plugin myself, I haven't focused on that yet. But I have seen, that you were basically required to duplicate the App.java code, which might be improved.

**Comment by vuvdoan** [comment]
thanks for fixing! :)

Regarding the maven plugin. Yeah, we were forced to "fake" the command line options and create the CommandParameters instance, since this instance will be referenced to in different singletons for example "APIMHttpClient". If we can get rid of this dependency, the maven plugin would look more clean in my opinion.

**Comment by cwiechmann** [comment]
Thanks for the feedback concerning the Maven-Plugin. I'll try to improve it in a future release by separating the Main-Class used from the Command-Line vs. calling it as a Lib.
