### ISSUE TITLE
[Help] Order property of a securityProfile

### ISSUE THREAD

**Issue by shan916** [Axway-API-Management-Plus/apimanager-swagger-promote#108]
**Swagger-Promote Version**
1.6.0

**API-Manager and Service-Pack Version**
7.5.3 SP7

**Question**
Can you clarify how the `order` property of a securityProfile should be used, specifically when using per method overrides?

**Additional information**
Looking at the `oauth-default-apikey-on-one-method` sample, it appears that the profile that is going to be applied on a specific method should have a lower order than the default security profile?

Could having the order specified incorrectly lead to any issues for the API at runtime?

**Comment by cwiechmann** [comment]
To my knowledge, the order property of a SecurityProfile doesn't matter for the runtime. It's only purpose is to show it sorted in the UI as it has been created.
