### ISSUE TITLE
[HELP] Retired status handling

### ISSUE THREAD

**Issue by lscalzotto** [Axway-API-Management-Plus/apimanager-swagger-promote#110]
**Question**
From the documentation, it seems the tool does not handle the retirement of APIs yet. Is there a plan to include this feature in the future? Also, is there a way to handle this case now?

**Comment by cwiechmann** [comment]
Just set the state attribute to: “deleted” and the API will be deleted in API-Manager.
Is this what you are looking for?

**Comment by lscalzotto** [comment]
Not exactly. I am looking for a process similar to the one that the Axway API Manager interface allows to do. That is: deprecate the API, specifying the retirement date (Manage selected context menu).
Is it possible to address this case with this tool?

**Comment by cwiechmann** [comment]
Set the status: “drepecated” and the desprecationDate. 
I’ll add some documentation for this scenario.

**Comment by lscalzotto** [comment]
Ok, thanks.
