### ISSUE TITLE
[Feature] Manage Remote Hosts

### ISSUE THREAD

**Issue by thotanaresh** [Axway-API-Management-Plus/apimanager-swagger-promote#114]
Does the tool has support to manage Remote Hosts? If not, is it planned or in your roadmap?

**Comment by cwiechmann** [comment]
No, today the tool doesn’t support remote host management.
Maybe, you can explain the use case and what exactly you would expect from the tool?
I mean details like
- should the management of remote hosts linked to an API or just have the remote host separated?
- should it be possible to link an API to an existing remote-host? And if the remote host doesn’t exists the API-Replication should fail?
- ....

**Comment by thotanaresh** [comment]
@cwiechmann ,

We have a couple of use cases to manage remote host:
- To increase the response timeout (default 30 secs to 60 secs) for a backend API, which does huge processing and takes a minute to get the response.
- To increase the response size (default to 10MB). We have a case where we have to download a file which is more than 10 MB

I guess, the remote host should link to API, I don't see any use case without a link.

**Comment by cwiechmann** [comment]
Swagger-Promote itself will not manage Remote-Hosts. Perhaps another dedicated Remote-Host module (which may be added somewhere in the future) may manage remote-hosts. 
I think that suche module is much more lightweight than handling APIs, as there are not so much dependencies. 

However, nothing which is planned short-team, hence I'm closing this for now.

**Comment by cwiechmann** [comment]
To keep track of this requirement and others that may come I created a dedicated project for it:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/projects/1
