### ISSUE TITLE
[BUG] MethodLevel - FaultHandlerPolicy send to API-Manager 7.5.3 - Leads to error unrecognized field

### ISSUE THREAD

**Issue by gfonteneau** [Axway-API-Management-Plus/apimanager-swagger-promote#115]
**Swagger-Promote Version**
1.6.0

**API-Manager and Service-Pack Version**
7.5.3 sp9

**Expected behavior**
Support for per method overrides for outbound profile working with API Mgr 7.5.3.

**Actual behavior**
a configuration for "method overrrides" is push by Swagger-Promote with an unwanted policy "FaultHandler" for all methode.
The code is actually removing the Fault-Handler for the Default-Profile only! That’s not correct.

**Test case sample**
> create a config file for outbound methode override and promote it.

**Comment by cwiechmann** [comment]
Hi @gfonteneau, I now fixed the code in the `OutboundProfileHandler` to make sure, that FaultHandlerPolicies are removed from all OutboundProfiles and not only the _default. 

Can you please validate the correct behavior with this Snapshot version: [apimanager-swagger-promote-1.6.1-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3469196/apimanager-swagger-promote-1.6.1-SNAPSHOT.tar.gz)

This fix will be included in the next release.

**Comment by cwiechmann** [comment]
This is fixed in version 1.6.1
