### ISSUE TITLE
Backup API and restore API functions in case of failures

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#117]
**Swagger-Promote Version**
1.5.3

**API-Manager and Service-Pack Version**
7.7

**Question**
Is it possible to have backupAPI functionality including all the info (orgs, apps, quota etc) in case if for some reason script failed and could not rollback so that we can apply the restore from the backup that was taken before running the script. I am more concerned if something happens in production, what are various ways we can get back to original API in case of failures.

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
The functionality you are looking for is actually not possible.
However, most of the time, when an API is published, it must be re-created as most of the properties are read-only. And in that case, Swagger-Promote doesn’t change the existing API until the new API is in place. When everything went good so far the existing API is deleted. That means, in case of an error, the existing published API is totally unchanged.
Further, it’s planned to add a export-function. This could be used as an additional step in your pipeline to create a backup yourself.
