### ISSUE TITLE
[BUG] Method-Level-Override broken after second import

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apimanager-swagger-promote#119]
**Swagger-Promote Version**
1.6.0

**API-Manager and Service-Pack Version**
7.6.2 SP3

**Expected behavior**
Method-Level-Overrides should be renewed in the same way as backend and frontend API.

**Actual behavior**
Method-Level-Override is broken after a second run-swagger-import run. It has now the title undefined and it is not possible anymore to edit it.

**Test case sample**
I imported an API with a configured Method-Level-override in the API configuration file.
e.g.
`"outboundProfiles":{
      "_default":{
         "authenticationProfile":"_default",
         "routeType":"proxy"
      },
      "getAddress":{
         "authenticationProfile":"_default",
         "parameters":[
            {
               "name":"AppId",
               "required":false,
               "type":"string",
               "paramType":"header",
               "value":"TEST",
               "exclude":false,
               "additional":true
            }
         ]
      }
   }`

If I run the import again (because something change in my Swagger file), the per-method-override seems to be broken. The name changed to undefined and I am not able to edit it anymore.

**Comment by cwiechmann** [comment]
@jschaefer77, thanks for reporting this. I can confirm this issue. 

I have created a dedicated Integration-Test for this scenario which is now, after I made a fix, is now passing through.

**Comment by jschaefer77** [comment]
Hi @cwiechmann, works now with the fix. 

Thank you very much. Great support.

**Comment by cwiechmann** [comment]
This is fixed in version 1.6.1
