### ISSUE TITLE
[BUG] Operating-System environment variable - Using variables in API-Config file

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#123]
**Swagger-Promote Version** 1.6.1
**API-Manager and Service-Pack Version** 7.6.2 SP3
**Expected behavior** set environment variable and it is replace in the config file during the import
**Actual behavior** the environment variable is not taken in consideration
**Test case sample**
> Please describe the steps you have done to replicate the issue
1. Create in your config file : "backendBasepath":"http://${myhostname}:8080"
2. export your variable : export myhostname=localhost + exécute your import

**Comment by cwiechmann** [comment]
Unfortunately I have to confirm that OS-Variables aren't working in version 1.6.1 😞 
To avoid any regression in future releases I will create a dedicated Unit-Test for that use-case and then fix the issue. I hope you can bypass the problem for now using env.proerties variables.

**Comment by cwiechmann** [comment]
Fixed in version 1.6.1-1 just released.
