### ISSUE TITLE
[Help] Difference between apimanager-promote & swagger-promote

### ISSUE THREAD

**Issue by Altaf-Axway** [Axway-API-Management-Plus/apimanager-swagger-promote#130]
**Swagger-Promote Version**
swagger-promote-1.6.1-1

**API-Manager and Service-Pack Version**
we are using 762 with SP4

**Question**
What are the major differences between the apimanager-promote of apigatway/posix/bin and swagger promote 

**What I've tried so far**
We have tried both but now we want to understand the difference and advantages of each process or if both are same.

**Additional information**
Both the process are nearly same just we want to create a CD-CI pipe line and we want to explore which is the best option to promote API on manager

**Comment by cwiechmann** [comment]
Hi @Altaf-Axway, 
The major difference is that the starting-point of your CI/CD-Pipeline: 
With apimanager-promote you need to use an API-Manager to manage your APIs, which is an additional overhead to API-Developers to do. They don't want to manage their APIs separately to make them compatible with the API-Manager.
With Swagger-Promote an API-Developer can use any tool or framework (e.g. Code-Generators) that is able to produce a Swagger-File and connect his APIs directly with the API-Management platform. 

The intention is to put your APIs under version control and by that you have something I call: APIs as Code similar to infrastructure as code. Perhaps review this slide-deck:
https://www.slideshare.net/Axway/streamline-api-management

There are many reasons why it's better to start with the Swagger-File:
- Deploy your APIs directly into the API-Management platform
  - you can repeat this over and over again, for instance on a change in your Swagger-File
    - adding new methods, parameters, etc. 
    - Doing this by hand in API-Manager is a pain and error-prone
- Staging your APIs becomes a matter you deployment
  - you can easily deploy your APIs into different environments, having different requirements
    - Security-Requirements, other Custom-Policies, etc.
- the Swagger-File is a Standard-Format, the API-Export DAT-File is not 
  - the API-Export Dat-File format is changing from API-Manager version to the next
    - as it is a kind of a Memory-Dump written to a JSON-File
    - as the internal data-structure is changing, the export-format is changing
  - the becomes important when you update your API-Manager and you can't import your existing API-Export files anymore
    - see this discussion here: https://community.axway.com/s/feed/0D52X00007XjEWdSAN
- Swagger-Files and the API-Configs are simple JSON-Files 
  - easy to read, easy to compare revisions, easy to rollback if needed, easy to audit
  - you can work collaborative on it using the Git-Flow (e.g. Pull-Requests, etc.)
  - existing tools can be made part of the CI/CD-Pipeline
    - e.g. validating the Swagger-File according corporate rule set
    - test your APIs with an existing test tool
    - etc. 
  - there are many useful tools out there, but non of these will work with the Custom Export-Dat file

In one sentence I would say:
With Swagger Promote your CI/CD pipeline starts with the API (the Swagger-File + Config) itself and it can be registered directly & repeatable into the API-Management platform. This streamlines the API-Lifecycle dramatically.

**Comment by cwiechmann** [comment]
Started with a new FAQ-Page and added this answer from here to it:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/FAQ
