### ISSUE TITLE
[BUG] Special caracters such as "é'èàô" are processed incorrectly

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#131]
Hello,

If in your swagger file for the description of the api backend you have : "développé l'aide".
Post deployment of your APIs, the result will be shown with a "square and question mark Inside"

**Comment by Rennaud** [comment]
Here is the result in API Manager :
![Capture](https://user-images.githubusercontent.com/53940634/63510805-d9108380-c4df-11e9-99d2-f7d08d87dcfc.jpeg)

**Comment by cwiechmann** [comment]
Thanks for reporting this @Rennaud. You identified a bug as Swagger-Promote must parse the Swagger-Files using Unicode encoding. I'll fix that in the next release.

**Comment by cwiechmann** [comment]
Hi @Rennaud, Unfortunately I was only partially able to validate the problem you are experiencing. The sample description I placed in the Swagger-File is processed as expected. 
Additionally I made some tests if special-characters in the API-Config file are causing a problem as well. And here I found an issue, which I have fixed. 
This is how it looks like for me:
![image](https://user-images.githubusercontent.com/16292002/63543722-ba33e080-c523-11e9-89f6-ef7d97550278.png)

When reading in the Swagger-File I have already used UTF-8 encoding. Can you please validate and confirm that your Swagger-File is saved as UTF-8?

**Comment by Rennaud** [comment]
Hi, 

You're right, it a strange thing as in Notepad++ it says UTF8 but on the server with the command file -bi filename : text/plain; charset=unknown-8bit

I have modified it to an UTF8 file and the special characters are handle correctly.
