### ISSUE TITLE
[Help] Question about the roll back on failure"

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#132]
Hello,

The documentation says : "If something goes wrong, the tool automatically rolls back all changes it made so far to leave the API-Manager instance in a clean state."

In my case I had an error on the client-Application : Application does not exist.
But no roll back has been done. What kind of error would be considered for a roll back?
I only find out something about this kind of case : 

> Create new BE-API/FE-API --> Configured FE-API --> Failure --> Delete new FE- and BE-API

Is it something missing in the rollback?

![Capture 2](https://user-images.githubusercontent.com/53940634/63525084-62827e80-c4fd-11e9-800e-3aea7f66e24e.PNG)

**Comment by cwiechmann** [comment]
Hi @Rennaud, the rollback only happens, when the API itself couldn't be configured properly or an unexpected error happens. 
In case of the application management it's expected that sometimes a configured application is not present. Having in mind, that Applications can easily deleted from the API-Manager. To my opinion, that should not lead to a complete rollback of the API. 

FYI: At the moment, the behavior for organizations is different. If an unknown Client-Organization is configured, the API is rolled back. I'm not sure, if this behavior really makes sense. I'm thinking about to change it, that it behaves in the same way as it's right now for applications.

**Comment by Rennaud** [comment]
Hi, Thanks for your quick answer. 

For the Client-Organization, it makes sense as you cannot create an API without an Organization (same behaviour with apimanager-promote). In my point of view having it is not a bad choice

**Comment by cwiechmann** [comment]
@Rennaud, the Client-Organizations are the organizations that should have access to your API, not the owing development organization. Hence, you can have configured some Client-Orgs that don't exists and those Orgs are ignore, but the API itself can be fully configured. 

Any thoughts?

**Comment by cwiechmann** [comment]
Now unknown client orgs no longer lead to an error.

**Comment by cwiechmann** [comment]
Has been fixed/enhanced in release 1.6.2.
