### ISSUE TITLE
How to do swagger promote for multiple apis?

### ISSUE THREAD

**Issue by RadhaR4** [Axway-API-Management-Plus/apimanager-swagger-promote#134]
**Swagger-Promote Version**

**API-Manager and Service-Pack Version**

**Question**

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Swagger-Promote as the core component is **not** supposed to handle multiple APIs in one execution.

If you need to process multiple APIs, I recommend to write your own wrapper (e.g. Shell-Script), which may iterate over a directory/list/etc. and calls Swagger-Promote for each API individually.

**Comment by cwiechmann** [comment]
Created a an FAQ-Entry for that question. https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/FAQ#how-to-do-swagger-promote-for-multiple-apis
