### ISSUE TITLE
[BUG]  The protocol of the backend URL is force to https : backendBasepath = http is change to backend url = https

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#136]
Hello,

The protocol of the URL is force to https.
In my configuration file if I put : 
"backendBasepath":"http://localhost:8010"
After the deployment, in API Manager we have "https://localhost:8010"
![image](https://user-images.githubusercontent.com/53940634/63693254-dd0c1080-c813-11e9-90ac-7fa2cce9f1a3.png)

That gives you a warning on frontend API because you don't have Trusted SSL imported.

**Comment by cwiechmann** [comment]
@Rennaud, yes I agree this needs to be improved. I experienced the same problem as well. 

I think a very likely fix will be, that Swagger-Promote will also use the protocol (HTTPS, HTTP) from the configured backendBasePath to change the "scheme" in the provided Swagger-File in the same way as the host & basepath is already changed.

**Comment by Rennaud** [comment]
In the swagger file I have : 
>   "schemes": [
>     "http",
>     "https"
>   ],

That's why we though that we were able to choose with the configuration files the protocol to use.
So swagger-promote will have to replace the schemes by only this
>   "schemes": [
>     "http"
>   ],
I guess that he will have to replace everything between the "schemes":[ <whatever_I_have_in_it> ]

**Comment by cwiechmann** [comment]
After I made the change I have in mind, everything depends on the configured backendBasePath and the given protocol. This will be used, to replace:
```json
  "schemes": [
    "https"
  ]
```
as you already guessed. Do you think that will support your use-case?

**Comment by Rennaud** [comment]
Yes, it will support my use-case.
Using the value in the backendBasePath to replace the value schemes present in the swagger file of the API.

Note : the value in the scheme could be multiple : 
`"schemes": [
"http",
"https"
],`

**Comment by cwiechmann** [comment]
Yes, and it will be replaced by the one given in backendBasePath

**Comment by cwiechmann** [comment]
Has been fixed/enhanced in release 1.6.2.
