### ISSUE TITLE
[BUG] The modification of the development Organization is not considered as a change

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#138]
**Swagger-Promote Version** - 1.6.1

**API-Manager and Service-Pack Version** - 7.6.2

**Question** - The development organization should be considered as a modification?

**What I've tried so far** - 
An API has been deployed with swagger-promote with the organization named "TEST", configuration file : 
              **"organization":"TEST"**
Modifying the config file for the value of the development organization to this value:
             **"organization":"API Development"**
The deployment with swagger-promote will return : 
> 12915  WARN                   App| No changes detected between Import- and API-Manager-API
> No changes detected. Existing with RC: 0

But if you modify the version, it will take both modification (version + organization) and update the API.

**Comment by cwiechmann** [comment]
Now, also the change of an organization is considered and if changed, the API will be re-created. This is a No-Breaking change, as the API-Manager internal owning organization doesn't break anything for the consumers.

As before, if Swagger-Promote is executed by an OrgAdmin the configured organization doesn't matter.

**Comment by cwiechmann** [comment]
Has been fixed/enhanced in release 1.6.2.
