### ISSUE TITLE
Parameterise Port no in the Script Options

### ISSUE THREAD

**Issue by venu124** [Axway-API-Management-Plus/apimanager-swagger-promote#14]
By default current script runs against localhost:8075 but if we have two instances with its own portals with other running on 8076. This scenario can't be achieved with current options. Port can be made parameterized.

**Comment by cwiechmann** [comment]
I think this enhancement is valid and it should be easy to implement.

**Comment by cwiechmann** [comment]
Fixed with version 1.4.2
