### ISSUE TITLE
[Help] How to set client certificate to retrieve API definition from https endpoint (2way ssl)?

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apimanager-swagger-promote#145]
**Swagger-Promote Version**
1.5.2

**API-Manager and Service-Pack Version**
7.6.2 SP2

**Question**
If I try to launch swagger promote with a definition file that refers to wsdl url that is protected by two way ssl, so it requires a client certificate, how can I tell the tool to use a client certificate?

**What I've tried so far**
I tried adding the java system property javax.net.ssl.keyStore e javax.net.ssl.keyStorePassword but it doesn't seem to work.

**Additional information**
In the launch script I set the keystore and truststore in this way:

"$JAVA_HOME/bin/java" -Djavax.net.ssl.keyStore=$programDir/certs/keystore.jks -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.keyStoreType=jks -Djavax.net.ssl.trustStore=$programDir/certs/truststore.jks -Djavax.net.ssl.trustStorePassword=password -Djavax.net.ssl.trustStoreType=jks -Xms64m -Xmx256m -classpath "$CP" com.axway.apim.App $*

**Comment by cwiechmann** [comment]
Hi @gcornacchia, That's unfortunately not supported by Swagger-Promote as it's today. Perhaps you can make the required code-changes yourselves and build you own package. 
I'm happy to take in contributions around this topic.

See here for more details:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/7.1-Contribute-to-this-project
