### ISSUE TITLE
[BUG] Manual App-Subscription get lost on Unpublished API using an Org-Admin

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apimanager-swagger-promote#149]
**Swagger-Promote Version**: 1.6.2

**API-Manager and Service-Pack Version**: 7.7

**Expected behavior**
It is very natural, that Org-Admins are working on unpublished APIs and subscribe to them to test. For that, they might use a manual subscription using the API-Portal/API-Manager-UI and expect, that this subscription is taken over when updating their API.

**Actual behavior**
Actually, existing manually created app-subscription get lost on a **unpublished** API when using an Org-Admin account only.

**Comment by cwiechmann** [comment]
Fix delivered with release 1.6.3

**Comment by hakila** [comment]
Hi,
Could you please give an example for this? We can have apps subsscribe to a published API. To make any significant chnages(except image), script unpublishes and recreates API and puts back the subscribed apps. Is it not working? Please provide example.

**Comment by cwiechmann** [comment]
Hi @hakila, as you know, most of the properties of an API are "Read-Only" once you have published the API. That's why you see that Swagger-Promote is re-creating the API, because API-Manager works that way. 

Do you say, re-creating the subscriptions to consuming apps is not working? If yes, please file a new issue. Otherwise please clarify what you mean.

**Comment by hakila** [comment]
I want to test this scenario reported in bug but i did not understand clearly. Hence I am asking give an example so that I can test.

**Comment by cwiechmann** [comment]
The issue was about that manual created Application-Subscriptions using the API-Manager are getting lost, when:
1. The API is in state unpublished 
2. And an Org-Admin is used
3. And the API needs to be re-created (e.g. changing the Swagger-File).

Now, that manual subscriptions are re-created even if the API is unpublished.
