### ISSUE TITLE
[Feature] Impove V-Host support

### ISSUE THREAD

**Issue by wsalembi** [Axway-API-Management-Plus/apimanager-swagger-promote#152]
**User story**
We often create multiple feAPI for a single beAPI using multiple vhosts (INTERNET, EXTRANET, INTERNAL access, etc). Each feAPI could have a specific Inbound Security Policy or documentation.

We would like to keep the information together in 1 api-config.json file (so supprot for multiple vhosts).

If it's not feasible, at least api-export must support to pass a vhost to specify exactly which API must be exported and import must do the replacement of the correct feAPI matching the same vhost.

**Additional context**

**Comment by cwiechmann** [comment]
V-Host support improved. With the next version:
A given V-Host is used as a key in addition to the API Exposure-Path. Previously, changing a V-Host of an API-Config has just updated the configured V-Host of the existing API. With this change, a new API with a different V-Host is created as the V-Host is now a key to identify an existing API.

When exporting an API, the V-Host is also taken into account. When an API has a configured V-Host it is exported into a Sub-Directory named like the V-Host. With that, all APIs belonging to the same V-Host are exported into the same Sub-Directory.
If no V-Host is configured, the API is exported directly into the given export folder.

These changes will be part of the next release.
