### ISSUE TITLE
[Feature] Use shorthand keys for APIGW policy references

### ISSUE THREAD

**Issue by wsalembi** [Axway-API-Management-Plus/apimanager-swagger-promote#154]
**User story**
Using api-export, some policy references only specify the policy name (requestPolicy, responsePolicy, routingPolicy). Other ones use the XML portable key notation (authenticationPolicy, etc)
We would like to standardize on the more readable shorthand key notation everywhere
e.g /[CircuitContainer]Main/[CircuitContainer]Common REST Security/[FilterCircuit]Handle REST Security

**Additional context**

**Comment by cwiechmann** [comment]
Hi @wsalembi, esp. for the reason to make it as easiest as possible for the developer, Swagger-Promote is only using the Policy-Name as a reference.
These Policy-Names are the ones, that appear in the API-Manager for selection. 

Also api-export should translate the Long-Names into the Short-Policy reference. If you find a situation, where Swagger-Promote doesn't do this conversion, please raise a bug.
