### ISSUE TITLE
[Feature] Multiple stages 

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#155]
**User story**
>1 - Application developer will create the swagger file : swagger_myAPI.json + minimal config file : config_myAPI.json (with empty value for info that he don't have such as Organization)
>2 - Internal developer will create all the configuration (that is not in the minimal config) for security inbound, outbound, quota, etc... : config_myAPI.stage1.json
>3 - Internal developer will create another stage file for the production that for example will change the quota value : config_myAPI.stage2.json
>4 - the deployment will accept the commande : "-s stage1,stage2" the stages are presented by order, that means stage1 will override the minimal config and stage 2 will override the minimal config and stage1 config.

**Comment by druppelt** [comment]
Just out of curiosity, what is the benefit compared to multiple config files?
````
./scripts/run-swagger-import.bat \
  -a swagger.json \
  -c config.json \
  -c int.json \
  -c oauth-int.json \
  -s dev-pre-int \
  -u username \
  -p pswd
````

**Comment by Rennaud** [comment]
Is it possible to use multiple configuration files? 
In order to override a configuration the wiki said it has to be use by the staging. So you can just add the configuration that need to be override and not the whole configuration.

**Comment by cwiechmann** [comment]
Hi @Rennaud, you can also overwrite the complete configuration for a specific stage if you want, but I'm not sure if this makes sense. 

The idea was to make it simple for developer. For instance when taking the "API-Name", it's very likely the same on all stages. And with that overwrite concept the developer maintains the name in the primary config-file and only the differences (e.g. Backend-Host) on the per stage config-file.

**Comment by cwiechmann** [comment]
@druppelt, multiple configure-files are not supported.

**Comment by cwiechmann** [comment]
I'm going to close that enhancement request now. Perhaps you can use a wrapper-script that merges the config-files, before finally calling Swagger-Promote. This may work for your use-case.
