### ISSUE TITLE
Error : Could not find or load main class com.axway.apim.App

### ISSUE THREAD

**Issue by lynxfg** [Axway-API-Management-Plus/apimanager-swagger-promote#16]
Hello,
I'm very happy to work with your plugin, your documentation is clear and very complete. 
I followed the instructions in the documentation, but I have the following error throwing the command
scripts/run-swagger-import.sh : 

Error: Could not find or load main class com.axway.apim.App

Do you have an idea about the source of the problem?

Best,

**Comment by cwiechmann** [comment]
Hi, 
This is very likely a Classpath-Problem. Could you please let me know on which operating-system you start the script?

Cheers,
Chris

**Comment by lynxfg** [comment]
I use the Windows operating system Windows

**Comment by rathnapandi** [comment]
Use following command in windows OS
java  -cp lib;lib\* com.axway.apim.App -a samples/petstore.json -c samples/Sample1.txt -h localhost -u apiadmin -p changeme

**Comment by cwiechmann** [comment]
Thanks @rathnapandi! I would say almost. You missed a "/" in your example. With that it works:

`java -cp lib;lib/* com.axway.apim.App -a samp....`

Perhaps it's a good idea to add a bat-file to the release.

**Comment by gwandwingor** [comment]
Hi, we had the same problem when executing the script from a git-bash terminal on windows.
I created a .bat version of the run-swagger-import.sh.

[run-swagger-import.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/2909251/run-swagger-import.zip)

Hope this helps.

**Comment by lynxfg** [comment]
Hello,

thank you very much for your help, it works for me perfectly.
I was able to launch the command from windows.

Best regards,

**Comment by cwiechmann** [comment]
@gwandwingor, this is great! Thanks! I'll include this bat-file into the package!

**Comment by cwiechmann** [comment]
Just released version 1.3 including the provided bat-file.
