### ISSUE TITLE
swagger promote script hangs 

### ISSUE THREAD

**Issue by RadhaR4** [Axway-API-Management-Plus/apimanager-swagger-promote#163]
swagger promote script hangs  when there is change in backend url and virtual host in the config file.

**Swagger-Promote Version** 1.6.2

**API-Manager and Service-Pack Version**
7.7

**Expected behavior**
The script should not hang and it should replace the backend url and virtual host

**Actual behavior**

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by RadhaR4** [comment]
Example Config file:
{
    "name": "ABSMemberInquiry",
    "path": "/absmemberinquiry",
    "state": "published",
    "version": "1.0.0",
    "organization": "Development",
    "backendBasepath": "http://internal.services-test.com/hn/mbrcomposite",
    "vhost": "apimgr8065.ckp-dev.com",
    "securityProfiles": [
        {
            "name": "_default",
            "isDefault": true,
            "devices": [
                {
                    "type": "authPolicy",
                    "name": "Invoke Policy",
                    "order": 1,
                    "properties": {
                        "authenticationPolicy": "BasicAuth",
                        "useClientRegistry": true,
                        "subjectSelector": "authentication.subject.id",
                        "descriptionType": "original",
                        "descriptionUrl": "",
                        "descriptionMarkdown": "",
                        "description": ""
                    }
                }
            ]
        }
    ],
    "caCerts": [
        {
            "certFile": "certificates/Corporate RootCA.pem",
            "useForOutbound": true,
            "useForInbound": false
        },
        {
            "certFile": "certificates/SUBCA1.pem",
            "useForOutbound": true,
            "useForInbound": false
        }
    ],
    "outboundProfiles": {
        "_default": {
            "authenticationProfile": "_default",
            "routePolicy": "Routing",
            "faultHandlerPolicy": "Fault Handler"
        }
    }
}

**Comment by RadhaR4** [comment]
Example Swagger file:
{
    "swagger": "2.0",
    "host": "basepath.org",
    "basePath": "/absmemberinquiry",
    "schemes": [
        "http"
    ],
    "paths": {
        "/*": {
            "get": {
                "description": "",
                "operationId": "GET",
                "tags": [],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            },
            "put": {
                "description": "",
                "operationId": "PUT",
                "tags": [],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            },
            "post": {
                "description": "",
                "operationId": "POST",
                "tags": [],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            },
            "delete": {
                "description": "",
                "operationId": "DELETE",
                "tags": [],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            },
            "patch": {
                "description": "",
                "operationId": "PATCH",
                "tags": [],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            }
        }
    },
    "tags": [],
    "info": {
        "title": "ABSMemberInquiry",
        "description": "",
        "version": "1.0"
    },
    "x-axway": {
        "corsEnabled": true,
        "basePaths": [
            ""
        ],
        "serviceType": "rest",
        "deprecated": false,
        "tags": {},
        "customProperties": {}
    }
}

**Comment by RadhaR4** [comment]
Below is the output with debug logs enabled. I updated the vhost and the backend url in the config.json and when I ran the swagger-promote, it hung on me.

------------------------------------------------------------------------
API-Manager Promote: 1.6.2 - I M P O R T

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
7      DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
3128   INFO     APIManagerAdapter| API-Manager version is: 7.7.0
3288   DEBUG IImportConfigAdapter| Current path=/home/jason/swagger-promote-1.6.2
3296   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/home/jason/legacy_apis/dev/swaggers/M360MKPExtractAPI' (relative path)
3309   DEBUG         APIDefintion| Replacing existing host: 'basepath.org' in Swagger-File to 'm360-mkp-ck-lstnr.ckp-dev.centene.com' based on configured backendBasepath: 'https://m360-mkp-ck-lstnr.ckp-dev.centene.com/api'
3309   DEBUG         APIDefintion| Replacing existing basePath: '/m360/mkp-checks-extract' in Swagger-File to '/api' based on configured backendBasepath: 'https://m360-mkp-ck-lstnr.ckp-dev.centene.com/api'
3310   DEBUG         APIDefintion| Replacing existing protocol(s): '["http"]' with 'https' according to configured backendBasePath: 'https://m360-mkp-ck-lstnr.ckp-dev.centene.com/api'.
3310   INFO          APIDefintion| Used the configured backendBasepath: 'https://m360-mkp-ck-lstnr.ckp-dev.centene.com/api' to adjust the Swagger definition.
4459   INFO     APIManagerAdapter| Found existing API on path: '/m360/mkp-checks-extract' (published) (ID: 'bb61ce7f-c3f2-4ec1-a26b-508b3dcb7ea2')
4893   DEBUG    APIManagerAdapter| Loading existing apps from API-Manager.
5584   DEBUG    APIManagerAdapter| Loaded: 184 apps from API-Manager.
7213   DEBUG       APIChangeState| No change for property: APIDefinition[Desired: 'com.axway.apim.swagger.api.properties.APIDefintion@7a8c8dcf' vs Actual: 'com.axway.apim.swagger.api.properties.APIDefintion@24269709']
7213   DEBUG       APIChangeState| No change for property: caCerts[Desired: '[CaCert [name=CN=Corporate RootCA, md5Fingerprint=0E:90:B3:E8:AB:F4:D2:9C:0E:27:CF:3F:0E:69:7F:0F], CaCert [name=CN=Centene OFL SUBCA1,DC=CENTENE,DC=com, md5Fingerprint=F9:B9:CA:74:FC:69:B3:B6:92:3A:5F:57:55:3A:90:6B]]' vs Actual: '[CaCert [name=CN=Corporate RootCA, md5Fingerprint=0E:90:B3:E8:AB:F4:D2:9C:0E:27:CF:3F:0E:69:7F:0F], CaCert [name=CN=Centene OFL SUBCA1,DC=CENTENE,DC=com, md5Fingerprint=F9:B9:CA:74:FC:69:B3:B6:92:3A:5F:57:55:3A:90:6B]]']
7213   DEBUG       APIChangeState| Ignoring Null-Property: descriptionType[Desired: 'null' vs Actual: 'original']
^C

**Comment by cwiechmann** [comment]
@RadhaR4, Thanks for reporting this issue with all the details. 

Unfortunately I wasn't able to re-produce the issue locally, but I had similar issues some time before in other areas, caused by Not-Closed HTTP-Responses. Therefore I made a change to make sure, that all created HTTP-Responses (after sending HTTP-Request to the API-Manager) are properly closed.
[apimanager-swagger-promote-1.6.3-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3656256/apimanager-swagger-promote-1.6.3-SNAPSHOT.zip)

I'm confident that the issue is solved by that, but unfortunately I need to ask you or the customer to validate it.
Besides that change, this version also contains some other small fixes, which will become part of the release 1.6.3. 
- Support for 7.7 SP1 & 7.6.2 SP5
- Private Keystore-Handling improved when using Outbound SSL (#147)
- A fix for App-Subscription when using an Org-Admin account only (#149)
- A fix in Custom-Policy-Handling, when using only one Custom-Policy ( #156)

I'll release this version very soon.

**Comment by RadhaR4** [comment]
Thankyou for the fast fix on this issue..
Customer validated with changing description and that works..
However they are still validating with changing backend url and virtual host.we will keep you posted.

**Comment by cwiechmann** [comment]
Fix delivered with release 1.6.3
