### ISSUE TITLE
[BUG] API Export with OrgAdmin credentials not possible

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apimanager-swagger-promote#168]
**Swagger-Promote Version**
1.6.3-SNAPSHOT

**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**
API Export should be possible even with OrgAdmin credentials.

**Actual behavior**
API Export only possible with Admin credentials.

**Test case sample**
> Please describe the steps you have done to replicate the issue
Run API-export with an unpublished API and with OrgAdmin credentials.

**Comment by cwiechmann** [comment]
@jschaefer77, created some integration tests to simulate an Org-Admin only is exporting APIs and made the required changes. 

Please note, that APIs exported by an Org-Admin are restricted as the Org-Admin cannot read all details from the API-Manager:
- No Quotas has been exported for the API
- No Client-Organizations
- Only subscribed applications from the Org-Admins organization

**Comment by jschaefer77** [comment]
Hi @cwiechmann,
thx. Also for pointing out the limitations.

**Comment by cwiechmann** [comment]
Fix delivered with release 1.6.3
