### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by stevebower59** [Axway-API-Management-Plus/apimanager-swagger-promote#169]
**Swagger-Promote Version** 
1.6.3-SNAPSHOT

**API-Manager and Service-Pack Version**
7.6.2 SP3

**Question**
If I specify the BackendBasePath parameter to change the host/basepath for other environments, will the api-import utility automatically download and change the SSL certificates in the caCerts section of the api-config.json if required, (if the host has changed and has a different SSL certificate than the original) or do the certs for the new environment need to be downloaded before-hand and updated in the appropriate stage api-config-xxx.json file.  

I think the API manager GUI does this if changing the backend URL .

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Hi @stevebower59, also with Swagger-Promote the API-Manager internally is downloading the Server-Certificates when using an HTTPS endpoint. This happens, when the Front-End-API is initially created. 

If you have configured CA-Certs in the API-Config file, Swagger-Promote will then overwrite all downloaded certificates, with the ones that has been configured. 
That means, Swagger-Promote does not update the API-Config on it's own with the certificates of the belonging backend-path. 

I have two recommendations:
- skip the ca-certs section in the api-config file and leave it to the API-Manager to download the correct certificates. 
- use variables that point to the right certificates depending on the stage you promote an API too. Using variables [see here](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.-API-Configuration#using-variables-in-api-config-file)

I hope this information helps!
Chris

**Comment by cwiechmann** [comment]
And I forgot to mention, using references like the below is good choice:
"certFile": "/my/path/to/certificates/${stage}/GoDaddySecureCertificateAuthority-G2.crt"
