### ISSUE TITLE
Does Swagger promote 1.6.2 and above works with 7.5.3 SP6 api manager?

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#175]
**Swagger-Promote Version**
1.6.2

**API-Manager and Service-Pack Version**
7.5.3 SP6

**Question**
I see in the release notes https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/1.-How-to-get-started#export-existing-apis-from-a-running-api-manager that 7.6.2 and above api manager versions have been tested. We are still on 7.5.3 SP6. Is it possible to test all your swagger promote versions on 7.5.3? Please let us know. Is there any limitation to use swagger promote for 7.5.3. please suggest the correct path that is suitable for 7.5.3.

**What I've tried so far**
We have only one environment in 7.7 but all are on 7.5.3. We are trying to see swagger promote versions are good with all versions i.e 7.5.3 and above.

**Additional information**

**Comment by cwiechmann** [comment]
Hi @hakila,

You can execute the integration tests yourself. Having the API-Manager up & running.
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/7.1-Contribute-to-this-project#running-tests

Please have in mind that these integration test will insert a considerable number of APIs, Apps und Organizations into the API-Manager. Therefore don’t execute it on a production or pre-production environment. Better is to have a dedicated instance just running for that purpose.

**Comment by hakila** [comment]
Does that have a feature to delete apis that were created once testing is done?

**Comment by cwiechmann** [comment]
No. There isn’t such option.
