### ISSUE TITLE
[Help] on run-swagger-import.sh deprecation

### ISSUE THREAD

**Issue by Shawcs** [Axway-API-Management-Plus/apimanager-swagger-promote#176]
**Swagger-Promote Version**
1.6.3

**API-Manager and Service-Pack Version**
7.6.2 SP04

**Question**
in run-swagger-import.sh you say 
>>>> This script is DEPRECATED and will be removed in a future release. Please use 'api-import.bat' instead.

but isn't **api-import.sh** that we will need to use instead ? 

As i'm on linux I can't use bat file and as far as I can see api-import.sh is quite similar to run-swagger-import.sh

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Yes, use api-import.sh. Sorry for the confusion. I will adjust the warning message.
