### ISSUE TITLE
Host Change with backendBasepath and automatic download of new certificates for promotion

### ISSUE THREAD

**Issue by stevebower59** [Axway-API-Management-Plus/apimanager-swagger-promote#178]
**Swagger-Promote Version**

**API-Manager and Service-Pack Version**

**Question**
I had two questions.
1)  Under what circumstances will the backendBasepath change the hostname in the swagger file (assuming replaceSwaggerInFile= true).
Some of the developers are specifying the backend URL with:

"basePath" : "https://hostname",
"resoucePath" :  "/mybackendpath"

some are using:

"host" : "myhostname",
"schemes" : ["https"],
"basePath" : "/mybackendpath"

and others are specifying the whole URL on the basePath in the Swagger:

"basePath" : "https://hostname/mybackendpath"
"resourcePath" : "/"

The only one I've been able to get to correctly work is for the one where the hostname is specified in the "host" parameter (example #2).

Are the other definitions valid, and we should be advocating them to specify the backend with  
option #2, or will the  backendBasepath URL in the "staging" api-config.mystage.json work for the other cases?

My second question, is a followup with another question I asked regarding the automatic download of certs.  You mentioned that the certs will be automatically downloaded by the API Manager on import if you remove the references to the certificates from the api-config.json for the API and the hostname has changed.   

Since I am doing an export of the original API and re-importing the exported API into another environment with a script, I was wondering if we could the removal of the certificates from the original api-config.json before using it for the import.   I tried specifying the certs parameter as an empty array in the api-config.xxx.json to override the original definition, but that did not seem to work.  

The only way I was able to get it to work was to removed the certs parameter from the original api-config.json file for the API before re-importing the API into the next environment.  That seemed to work as expected.

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Hi @stevebower59, 

`host`, `schemes` and `basePath` are modified by Swagger-Promote based the configured backendBasepath. If the host/schemes/basePath is given in other parameters they are not modified. Hence I do recommend to set the host and schemes according to the specification:
https://swagger.io/docs/specification/2-0/api-host-and-base-path

Concerning your second question. Swagger-Promote only ignore properties, such as certs, when they are `null`. Declaring an empty array for certs means you want no certificates.

You could try to setup the following in you api-config.xxx.json:
```json
certs:null
```
If this is accepted by the parser (which I assume), certs will be null internally and Swagger-Promote should not overwrite the downloaded certificates.

Hope this works!

**Comment by cwiechmann** [comment]
No feedback. Closing this issue now.
