### ISSUE TITLE
Help Automatically changing OAUTH Endpoint URLS in Security Profiles section when promoting to another environment

### ISSUE THREAD

**Issue by stevebower59** [Axway-API-Management-Plus/apimanager-swagger-promote#179]
**Swagger-Promote Version**
1.6.3

**API-Manager and Service-Pack Version**
7.6.2 SP3

**Question**

Is there an easy way to change the OAuth Endpoints in the securityProfiles Section when moving the API from one environment to another?  

Or is the easiest way to include the securityProfiles element in the appropriate api-config.xxx.json override file for each environment.

  "securityProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "devices" : [ {
      "name" : "OAuth",
      "type" : "oauth",
      "order" : 1,
      "properties" : {
        "tokenStore" : "<key type='OAuth2StoresGroup'><id field='name' value='OAuth2 Stores'/><key type='AccessTokenStoreGroup'><id field='name' value='Access Token Stores'/><key type='AccessTokenPersist'><id field='name' value='OAuth Access Token Store'/></key></key></key>",
        "accessTokenLocation" : "HEADER",
        "authorizationHeaderPrefix" : "Bearer",
        "accessTokenLocationQueryString" : "",
        "scopesMustMatch" : "Any",
        "scopes" : "resource.WRITE, resource.READ",
        "removeCredentialsOnSuccess" : "true",
        "implicitGrantEnabled" : "true",
        "implicitGrantLoginEndpointUrl" : "**https://Apimdev.nov.com:8087/api/oauth/authorize**",
        "implicitGrantLoginTokenName" : "access_token",
        "authCodeGrantTypeEnabled" : "true",
        "authCodeGrantTypeRequestEndpointUrl" : "https://Apimdev.nov.com:8087/api/oauth/authorize",
        "authCodeGrantTypeRequestClientIdName" : "client_id",
        "authCodeGrantTypeRequestSecretName" : "client_secret",
        "authCodeGrantTypeTokenEndpointUrl" : "https://Apimdev.nov.com:8087/api/oauth/token",
        "authCodeGrantTypeTokenEndpointTokenName" : "access_code"
      }
    } ]
  } ],

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
For that you can use variables. Have a look here:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.-API-Configuration#using-variables-in-api-config-file

Let me know, if this helps.

**Comment by stevebower59** [comment]
I noticed that sometimes the api-export command returns a swagger 1.1. version of the Swagger API definition, and sometimes returns a swagger 2.0 version of the Swagger file.

But when  I download the Swagger file from the API Catalog from the Download Swagger 2.0 file from the API catalog weblink, I always get the swagger 2.0 definition.   

Is there a way to specify the swagger specification that api-export uses to export the Swagger file for the API, or does it always export the original version.    

It seems as though there is a swagger 1.1 -> swagger 2.0 function that the API catalog uses to convert it when downloading the swagger file through it's link...

**Comment by cwiechmann** [comment]
Let me investigate about the root cause. I can at least say now, that Swagger-Promote is not requesting any special version. So, nothing by intention.
It's using the REST-API to download the `original` Swagger-File. Maybe that's the difference. When downloading via the API-Catalog the generated Frontend-API-Swagger file is downloaded, which is always 

But for Swagger-Promote it is more important to get the original Swagger-File in order to compare it.

I'll come back to you on that when I know more.

**Comment by cwiechmann** [comment]
This is the code requesting the original API-Definition (e.g. Swagger, WSDL) from the API-Manager:
```java
uri = new URIBuilder(CommandParameters.getInstance().getAPIManagerURL()).setPath(RestAPICall.API_VERSION + "/apirepo/"+backendApiID+"/download")
		.setParameter("original", "true").build();
```
`apirepo` means to use the Backend-API and from there the originally imported Swagger-Definition. So, from there I would say that's correct.

@stevebower59, could it be, that the APIs you exported have used version 1.1 during import at that time?

**Comment by cwiechmann** [comment]
No feedback. Closing this issue now.
