### ISSUE TITLE
[BUG] 7.5.3 SP7 null certBlob issue on export

### ISSUE THREAD

**Issue by shan916** [Axway-API-Management-Plus/apimanager-swagger-promote#187]
**Swagger-Promote Version**
1.6.3-1

**API-Manager and Service-Pack Version**
7.5.3 SP7

**Expected behavior**
The API export should not fail if a `certBlob` is null for some API. For some reason, API Manager 7.5.3 SP7 has a `certBlob: null` in the export DAT file for certain APIs. I believe it makes sense for Swagger promote to ignore the cert export if the `certBlob` is null.

**Actual behavior**
There is a `NullPointerException` in the Base64 decode.

```
15336  WARN                CaCert| Could not create filename for certificate based on alias: OU=Go Daddy Class 2 Certification Authority, O="The Go Daddy Group, Inc.", C=US
15337  WARN                CaCert| Created a random filename: UnknownCertificate_3759.ctr
15341  ERROR            ExportApp|
java.lang.NullPointerException
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.axway.apim.api.export.APIExportConfigAdapter.storeCaCerts(APIExportConfigAdapter.java:145)
	at com.axway.apim.api.export.APIExportConfigAdapter.saveAPILocally(APIExportConfigAdapter.java:129)
	at com.axway.apim.api.export.APIExportConfigAdapter.exportAPIs(APIExportConfigAdapter.java:60)
	at com.axway.apim.ExportApp.run(ExportApp.java:128)
	at com.axway.apim.ExportApp.main(ExportApp.java:35)
```

**Test case sample**
Not sure how you would force the `certBlob` to be null. Maybe export a DAT file for an API and manually set the `certBlob: null` for one of the certs and re-import from DAT file? Then, try exporting the API.

This is an odd issue with API Manager since the exact same cert for a different API does not have `certBlob: null` in the DAT export.

**Comment by cwiechmann** [comment]
Fixed with release 1.6.3-2
