### ISSUE TITLE
[BUG]api-export.bat script search for apis on filesystem

### ISSUE THREAD

**Issue by snon-axway** [Axway-API-Management-Plus/apimanager-swagger-promote#196]
**Swagger-Promote version : 1.6.3-2**

**API-Manager and Service-Pack Version : 7.5.3 SP10**

**Expected behavior**
Run api-export script and get configuration file for the choosen api

**Actual behavior**
API not found and local path is added to path given with "-a" option

**Log-Output in Debug**

./api-export.bat -h localhost -u apiadmin -p changeme -a /apimanager/fridge/v1

API-Manager Promote: 1.6.3-2 - E X P O R T  
To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote

0      INFO  nvironmentProperties\| Trying to load environment properties from file: env.properties ... not found.
5      INFO  IExportConfigAdapter\| Going to export API: C:/Users/snon/AppData/Local/Programs/Git/apimanager/fridge/v1 to path: null
3714   INFO     APIManagerAdapter\| API-Manager version is: 7.5.3 SP10
3877   INFO     APIManagerAdapter\| No existing API found exposed on: 'C:/Users/snon/AppData/Local/Programs/Git/apimanager/fridge/v1'
3878   ERROR            ExportApp\| No API found for: 'C:/Users/snon/AppData/Local/Programs/Git/apimanager/fridge/v1'

 "C:/Users/snon/AppData/Local/Programs/Git" is added to the "-a" parameter which should only be "/apimanager/fridge/v1"

**Test case sample**
Publish an api on API Manager local instance
Try to use the export-api script

**Comment by cwiechmann** [comment]
I agree, that looks incorrect. Let me check.

**Comment by cwiechmann** [comment]
@snon-axway, I tried to reproduce the issue locally, but it's working as expected. The following Log-Message you see:
`Going to export API: C:/Users/snon/AppData/Local/Programs/Git/apimanager/fridge/v1 to path: null`
I driven by the following code line:
`LOG.info("Going to export API: " + exportApiPath + " to path: " + localFolder);`
And the variable: `exportApiPath` is directly take from the given input parameter: 
`params.getValue("api-path")` which is the same as "-a". 

That said, there must be something wrong how the parameters are transferred to the Java-Program. 

What is the Operating System you are using?
Do you use a Command-Line or Power-Shell to run the export?
Can you please try to quote the call? Like so: `-a "/apimanager/fridge/v1"`

**Comment by snon-axway** [comment]
Hi @cwiechmann,
I was using Gitbash on Windows.
I switched to powershell and it was ok. I think the issue can be closed.
Thanks for the answers.
