### ISSUE TITLE
Import tool matches ?singleWsdl to Rest instead of WSDL

### ISSUE THREAD

**Issue by henelyt** [Axway-API-Management-Plus/apimanager-swagger-promote#197]
**Swagger-Promote version**
1.6.3-2

**API-Manager and Service-Pack Version**
7.5.3 SP5

**Expected behavior**
?singleWsdl should import as a WSDL instead of Rest

**Actual behavior**
The URL matching does not catch this as a WSDL file and falls through to REST processing

**Comment by cwiechmann** [comment]
Will be part of the next release to be released very soon.
