### ISSUE TITLE
[Enhancement] Handling WSDL service with multiple bindings

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apimanager-swagger-promote#207]
**Swagger-Promote version**
> Please make sure to use the latest Swagger-Promote version.
1.6.3
**API-Manager and Service-Pack Version**
7.6.2 SP2 

**Expected behavior**
When you import a wsdl file from api manager with 2 soap bindings (1.1 and 1.2 soap version) it creates automatically 2 backend apis with 1.1 and 1.2 suffix. I suppose that API Manager cannot handle in the same endpoint 2 soap binding versions at the same time. 

**Actual behavior**
When I use swagger promote to do the same thing only one Frontend API is created (I supposed related to 1.1 binding) so when I try to invoke with 1.2 soap format the manager throws an error.

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

the public wsdl http://www.dneonline.com/calculator.asmx?WSDL contains the soap bindings in both version 1.1 and 1.2

**Comment by cwiechmann** [comment]
Not sure, if it is feasible to implement this requirement. At the moment I would say very unlikely.
