### ISSUE TITLE
[BUG] Can't reapply quotas to apps with special characters in their names

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apimanager-swagger-promote#209]
**Swagger-Promote version**
1.6.3-2

**API-Manager and Service-Pack Version**
7.5.3-SP10

**Expected behavior**
When I update an API, all the apps that were subscribed to this API need to remain subscribed and all Application quotas need to be preserved.

**Actual behavior**
An error is thrown for Apps having special characters in their names (such as french accents :éèöî).
Apps quota update is stopped, API is rollbacked but some quotas are lost in the process.

**Log-Output in Debug**
[api-import-quota-error.log](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3901081/api-import-quota-error.log)

**Test case sample**
1. Deploy & Publish the "Sample Minimal API"
2. Create an App named "Bière Géante" in the same Org as the API
3. In "Bière Géante" app, subcribe to "Sample Minimal API"
4. In "Bière Géante" app, override default application quota and apply a throttling quota for all "Sample Minimal API" methods
5. Change basepath in the 'petstore.json' swagger file to create a breaking change
6. Redeploy "Sample Minimal API"

**Comment by cwiechmann** [comment]
Thanks for the contribution Just merged into develop and will be part of the next release.
