### ISSUE TITLE
how to get api applications and their quotas to do post processing after api is created

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#213]
I am doing post processing after the api is created. I need to find out all the quotas for that api. I don't any easy way through rest calls
http://apidocs.axway.com/swagger-ui/index.html?productname=apimanager&productversion=7.5.3&filename=api-manager-V_1_3-swagger.json&_ga=2.68790290.248709392.1518117455-61184763.1514317881#/
other than iterate through all applications and find that api and then find quota. Please suggest.

**Comment by cwiechmann** [comment]
Hi @hakila, in version 7.5.3 you are using there is no direct way to retrieve the list subscribed applications for an API. 
So, there is basically no other way as to iterate over all applications. For versions below 7.7. Swagger-Promote is doing internally the same. 
In version 7.7 you have the following REST-API:
![image](https://user-images.githubusercontent.com/16292002/70078629-5087a000-1603-11ea-922e-a0c38533b934.png)

Just thinking, if it makes sense to export the actual state with all subscribed applications into the export file. Should be easy. Let me check.

**Comment by cwiechmann** [comment]
@hakila, Would it help, if the Post-Processing file contains the following line:
```
clientApplications=4e8634ba-6762-45ca-bbe5-7ca4e99192ac, f49947cb-e363-4d11-a14c-7530a5e9e28d, 0023daa-1586-4b79-9b5f-6ca8e0935a21
```
This is a list of Application-IDs, having an active subscription. This list might become huge, but I think this doesn't matter. Right?

**Comment by hakila** [comment]
that will definitely help. But it would be nice if there is rest api. As a user , I relate everything with api and it makes easy if we retrieve all the necessary information for an api without much hassle.

**Comment by cwiechmann** [comment]
Agree! As said, with version 7.7 you have that API you are looking for available, which returns all applications having a subscription and with that you can validate which has a configured quota. 7.5.3 becomes EOS Nov/2020 anyway, so maybe a good reason to think about a migration to 7.7 or 7.8 (to be released early next year).

**Comment by hakila** [comment]
Is API metadata(orgs, apps, quotas etc) planned to be available in the details file that is being generated as the output of swagger promote? I just consumed 1.6.5 and tested with 7.7 version but only feapiid is coming.

**Comment by hakila** [comment]
in the above you stated below is ok
clientApplications=4e8634ba-6762-45ca-bbe5-7ca4e99192ac, f49947cb-e363-4d11-a14c-7530a5e9e28d, 0023daa-1586-4b79-9b5f-6ca8e0935a21
along with ids if we also display name, it will be more convenient. otherwise we need to make another rest call to get the app name. This feature is very useful for us in debugging.
