### ISSUE TITLE
[Feature] Using variables in environment property files

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apimanager-swagger-promote#228]
Hi, 

I don't want to store my username and password in env property files.
I know, that I can run as well /api-import.bat using the -u and -p CLI parameter. The downside of this approach is, that the credentials are then displayed/logged in the CLI output.

What about a feature of using as well variables in env property files?
Then I can store my username and password using an environment variable and both values will not be logged/display in the CLI output.

regards Joerg

**Comment by gwandwingor** [comment]
Hi Joerg,

> I know, that I can run as well /api-import.bat using the -u and -p CLI parameter. The downside of this approach is, that the credentials are then displayed/logged in the CLI output.

If you run api-import.sh from within a Jenkins pipeline, one workaround could be to store those credentials as Jenkins credentials. This way, they don't get displayed in the build logs.
Dunno if it helps, just my two cents ...
Cheers,
Guillaume

**Comment by jschaefer77** [comment]
Hi @gwandwingor ,
ok, and how do you pass then the Jenkins credentials to api-import.sh. I assume you are using the -u and -p cli parameter?
Are Jenkins credentials comparable to environment variables? If so I can run something like the following, which is working fine now and does not display the value of the env settings in the CLI output.
`api-import ... -u %apim_user% -p %apim_password%`

regards Joerg

**Comment by gwandwingor** [comment]
Basically, you need to define your username & password in the Jenkins credentials, and then, using the [Credentials Binding plugin](https://jenkins.io/doc/pipeline/steps/credentials-binding/), you will be able to retrieve them as variables, that you can indeed pass to api-import.sh as environment variables.

There's a well documented section regarding how to handle credentials within Jenkins in the  [Jenkins online documentation](https://jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials).

Also, here's the piece of code I use in my pipeline. 

[api-import.txt](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/4122593/api-import.txt)

**Comment by jschaefer77** [comment]
thank you very much @gwandwingor for sharing the example,
for now I am fine with storing the username and password in an operating system environment variable instead of the env property file and passing it during api-import CLI call.
