### ISSUE TITLE
[Feature] request publication as org admin

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apimanager-swagger-promote#229]
**Swagger-Promote version**
> Please make sure to use the latest Swagger-Promote version.
1.6.4
**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**
If I run api-import only as an org admin, but with state published in api-config.json I would expect, that swagger-promote requests now the publication so that the new state is "pending approval". That would be the same behaviour as in API Manager UI as org admin.

**Actual behavior**
No import or publication requested because of the below listed errors.

**Log-Output in Debug**
8657   INFO        APIChangeState| Changed property: state[Desired: 'unpublished' vs Actual: 'published']
8666   ERROR     App| OrgAdmin user only allowed to change/register unpublished APIs.

**Test case sample**
> Please describe the steps you have done to replicate the issue
- Import API only with org admin credentials (state unpublished)
- Run import again but change the state to published

**Comment by cwiechmann** [comment]
Hi @jschaefer77, my initial thought on this was, that it makes sense to support this API-Manager feature also with Swagger-Promote like a final quality gate. 
However, I have some concerns to support it, as it might be very complicated to handle it, when thinking about the concept how Swagger-Promote works (Desired- vs. Actual-State). 

For instance having a situation, where an API is already in state "Published" and an updated API should replace that API, also declared state "Published". 
With that feature supported, it would stop replication with state: "Unpublished", while still having the other API: "Published". Now, we have the desired API two times in the API-Manager, which is by definition of the underlying concept not good.
On the next run, Swagger-Promote cannot identify anymore, which is the actual API and would fail. At this point a user-interaction (from an Admin) is required to solve the problem, which is also not good, as this user (or group) might become some kind of bottleneck.

As there is already a near-team [road-map](https://community.axway.com/s/api-management) item: "User and OrgAdmin Self Service" to better support Org-Admins, I would conclude not to support this feature in Swagger-Promote for now. Instead, once that Org-Admin-Improvement is available make Swagger-Promote compatible with that new behavior.

**Comment by cwiechmann** [comment]
Hi @jschaefer77, the attached version supports a flag/toggle, that allows Org-Admins to request a publish state. 
Set the flag: orgAdminPublishToApprove=true in either the env.properties or as a command-line parameter. 

[apimanager-swagger-promote-1.6.5-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/4218152/apimanager-swagger-promote-1.6.5-SNAPSHOT.zip)

Let me know, if this works for or if you have a better idea for toggle. I don't like that name, but nothing better came in my mind.

**Comment by cwiechmann** [comment]
Attached is a new version, which no longer considers a "published" APIs as actual. Instead it considers a still "pending" API as actual an updates this one.
Once, the "pending" API has been published (by an Admin) a new pending is created. That process should work pretty okay.

[apimanager-swagger-promote-1.6.5-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/4245414/apimanager-swagger-promote-1.6.5-SNAPSHOT.zip)

**Comment by cwiechmann** [comment]
For reference I already added how version 1.6.5 will support Org-Admin to request a publication.
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/6.-OrgAdmin-support
This is described as point: 2 Request for approval

**Comment by jschaefer77** [comment]
Hi @cwiechmann,
thx for the latest snapshot and the already provided documentation. Everything works now as expected. If I run swagger promote as OrgAdmin, IMO swagger promote is now consistent to the API Manager UI which is really great.

When do you plan to release this feature?

**Comment by cwiechmann** [comment]
Will be available by the end of this week latest.
