### ISSUE TITLE
[Help] How to manage published and unpublished APIs using the same path

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apimanager-swagger-promote#230]
**Swagger-Promote Version**
1.6.4

**API-Manager and Service-Pack Version**
7.6.2. SP4

**Question**
OrgAdmins using API Manager UI are able to import a second API using the same path. API Manager UI just shows a path conflict, but the import is still possible, As long as the first API is published and the second one unpublished, incoming calls will be routed to the published one.
OrgAdmins can now request publication and an API Manager admin can do a Zero Downtime Upgrade.

How can I manage such a scenario using swagger-promote with role orgAdmin only?
If there is already a published API using the same path I cannot import another unpublished one and request later the publication.

7025   INFO        APIChangeState| Changed property: state[Desired: 'unpublished' vs Actual: 'published']
7028   ERROR     App| OrgAdmin user only allowed to change/register unpublished APIs.

**What I've tried so far**

**Additional information**

**Comment by jschaefer77** [comment]
This issue is related to #229

**Comment by cwiechmann** [comment]
Hi @jschaefer77, Swagger-Promote has the concept of defining the desired state of an API and this state gets replicated into the API-Manager. To locate the actual API three criteria's are used: Path, V-Host and the API-Routing-Key (See [here](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.-API-Configuration#how-the-actual-api-is-looked-upped))

So, I would think supporting the use-case you described wouldn't fit with that concept. It would mean to make the **status** an API a criteria to locate the actual API in API-Manager, but this is nothing I want as it is an essential information of the desired API.

Instead, I think that Org-Admins should be allowed to update their APIs at any time they want in a Pre-Production system. With that, they can validate/test their APIs in a Self-Service-Fashion. 
Once an API is good for production, it gets promoted to production. And at this point it should be okay to immediately replace the actual API, without having an intermediate state (Published/Unpublished). As the API-Definition is version-controlled you can easily roll back to the previous version if there is an issue.

Another option is to use the API-Routing-Key to support two different APIs on the same path, but I would use it with caution and a good retirement plan. The API-Routing-Key might lead in the long run to have many very similar APIs doing almost the same thing. 
In worst case, each API version only having a few subscribers, which is some kind of a point-to-point communication, which nobody wants.

**Comment by jschaefer77** [comment]
Feature enhancement already provided with #229 
See also: https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/6.-OrgAdmin-support
