### ISSUE TITLE
[Help]  Invalid file The file does not contain a valid Swagger definition.

### ISSUE THREAD

**Issue by migoya2020** [Axway-API-Management-Plus/apimanager-swagger-promote#231]
**Swagger-Promote version**
> Please make sure to use the latest Swagger-Promote version.

**API-Manager and Service-Pack Version**

**Expected behavior**

**Actual behavior**

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

I get this info  whenever i try to import APi from spotlight.io
what am i doing wrong?

![Screenshot from 2020-01-31 13-42-06](https://user-images.githubusercontent.com/23479444/73533723-8b098f80-4430-11ea-8f29-05755c9fbfec.png)

**Comment by cwiechmann** [comment]
Hi @migoya2020, this repository isn’t for API-Builder nor Stoplight.
However, I’m happy to help. Next time I recommend to open an issue here: 
https://github.com/Axway-API-Builder-Ext/api-builder-extras

Can you share the error message you get when trying to import the Swagger-File? Or better share the Swagger-File you created.

**Comment by migoya2020** [comment]
i found the problem,   there was an error in my swagger file, this is fixed. thank you
