### ISSUE TITLE
[Help]can't import WS from my api subdirectory.

### ISSUE THREAD

**Issue by mmaaouni** [Axway-API-Management-Plus/apimanager-swagger-promote#232]
**Swagger-Promote Version**
1.6.4

**API-Manager and Service-Pack Version**
API-Manager 7.7

**Question**
can't import WS from my api subdirectory.

**What I've tried so far**

**Additional information**

**Comment by mmaaouni** [comment]
![import swagger erreur](https://user-images.githubusercontent.com/36197411/73863044-bda3f580-483f-11ea-875f-c5c4eea5f2fa.PNG)

**Comment by cwiechmann** [comment]
Hi @mmaaouni, 

It's very likely, that the API-Manager can't connect the host to automatically download the server-certificates. This is causing that kind of error quite often. This API-Manager behavior can't be disabled.

So, please make sure, that the host+port given in the Swagger-Definition is really reachable from the API-Manager host. 

To validate my guess, is really causing the error, please set the backend-host+port temporarly to an insecure HTTP protocol. The hostname for that test doesn't matter, as the API-Manager no longer tries to import the certificates:
`"backendBasepath":"http://any.host.com:8081/xyz/zzz",`

I will create a FAQ-Entry soon, as this issue appears over and over again.

**Comment by mmaaouni** [comment]
hi @cwiechmann 
Thank you for your answer. The import works when I put a random url. 
however it is not displayed as a backend on the API managers , the goal is to modify this url 
do you have any idea how I can import and modify the url.
thank you for your help
mehdi

**Comment by cwiechmann** [comment]
Can you please check this FAQ-Entry if this helps:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/FAQ#error-creating-api-proxy

**Comment by mmaaouni** [comment]
The need concerns the update of the WSDL backends

It doesn't take the basepathbackend modification on the api-config.json file but it takes the backend URL from the upstream environement

**Comment by cwiechmann** [comment]
Oh yes, you are right. The backendBasepath doesn't work with WSDL-Files. What do you mean by that: _"but it takes the backend URL from the upstream environement"_?

**Comment by mmaaouni** [comment]
I mean he takes the backend of the environment where the export was made.

**Comment by cwiechmann** [comment]
I guess, you mean that WSDL has been generated on a different environment, and contain hostnames from that environment.  
Unfortunately, Swagger-Promote doesn't support to adjust the hostnames inside the WSDL. Hence I'm afraid you have to correct them manually, for instance using a pre-processing script before handing the WSDL's over to Swagger-Promote.

**Comment by mmaaouni** [comment]
Hello Christophe,

I just tried the 1.6.5 snapshot version the script ignores the certificate management but I think that the import does not go further because my import falls on a 400 error. 

I test well the url of the wsdl in insecure in my server it recovers it well 

Here is the log : 
1626 ERROR RestAPICall| Response: 'HTTP/1.1 400 Bad Request'.
1626 ERROR App| Error importing BE-API. Unexpected response from API-Manager: HTTP/1.1 400 Bad Request {"errors":[{"code":400, "message": "Error retrieving content. Cause: Certificate for <apim-mutexapi-dev.axwaycloud.net> doesn't match any of the subject alternative names: []"}]}. Last request: 'POST POST https://apim-mutexapi-dev.axwaycloud.net:8175/api/portal/v1.3/apirepo/importFromUrl/?organizationId=254f352f-8977-4f62-8e2a-c6dad90b7a05&type=wsdl&url=https%3A%2F%2Fapim-mutexapi-dev.axwaycloud.net%3A8065%2Fselfcare%2Fwebservices%3FWSDL&name=espaceEmployeService HTTP/1.1'.

thank you for your help.
Mehdi Maaouni

**Comment by cwiechmann** [comment]
Hi @mmaaouni, I recommend to have a WebEx sorting this problem out. Can you please send me an email, so I can invite you? cwiechmann@axway.com

**Comment by mmaaouni** [comment]
I will be happy to send you an email according to your availability.

**Comment by cwiechmann** [comment]
Closing the issue with the comment:
_I finally found the source of my error the certificates associated with manager and the webservice ports did not contain an alternate name variable that refers to the DNS of the axway cloud which blocked the import in error 400.
I generated a new certificate on the port I have as reference and the import script works correctly._
