### ISSUE TITLE
Backend Service URL not displaying and Backend URL not using as specified in config

### ISSUE THREAD

**Issue by los3rz** [Axway-API-Management-Plus/apimanager-swagger-promote#234]
I imported an API specifying the backendBasePath to replaced with. However, when I check in the API Manager the backend URL is not showing. Refer image below. 

When calling an API, it is also not forwarding to the one I specified in backendBasePath but instead its using the inbound "path" specified in api config.

The replaceHostInSwagger properties is not defined in my env.properties which should default it to true.

![image](https://user-images.githubusercontent.com/4107525/74803984-ce616a80-5319-11ea-96d6-ffd9d3ed379d.png)

Update: Seems like config with outbound profiles causing the issue. My outbound profile as below.

"outboundProfiles" : {
    "_default" : {
      "routeType" : "policy",
      "routePolicy" : "Cache Routing Policy",
      "authenticationProfile" : "_default",
      "parameters" : [ ]
    }
  }

**Comment by cwiechmann** [comment]
Hi @los3rz, when using a Routing-Policy the API-Manager UI doesn't show the registered Backend-Service-URL. This is known and already tracked. 
However, the URL is made available to your routing-policy with the attribute: ${destinationURL}

I'm closing this issue now, if you have further questions, please re-open.
