### ISSUE TITLE
api-export - Overwrite existing API folder/files

### ISSUE THREAD

**Issue by Chillytwix** [Axway-API-Management-Plus/apimanager-swagger-promote#235]
Greetings.

I'm looking for some kind of "-force" parameter to overwrite the destination files when running api-export.bat. Screenshot attached

![Swagger-Promote](https://user-images.githubusercontent.com/18362628/75145438-3c7ea680-56f9-11ea-83c0-986fd6ec39d7.GIF)

Best regards
Marcelo Uboldi

**Comment by Chillytwix** [comment]
This sounds great Chris.
Thanks for adding this to version 1.6.5.

Any idea when this version will be available?

Best regards
Marcelo Uboldi

**Comment by cwiechmann** [comment]
I also would like to include issue #229 in 1.6.5, which is almost complete. I’m waiting for the final feedback.
You can expect the final release on Friday this week.
I’m closing that issue now as it is done.
