### ISSUE TITLE
How to avoid configuring the API's in API Manager with swagger promote using the same front end resource path ?

### ISSUE THREAD

**Issue by yatamraghu** [Axway-API-Management-Plus/apimanager-swagger-promote#238]
Hi Chris,

I would like to know is there any possibility to avoid publishing two API's with same front end resource path.
If yes can you provide me some help here.

Thanks

**Comment by cwiechmann** [comment]
Hi @yatamraghu, Perhaps the context of your question isn't fully clear to me. 

By default, Swagger-Promote will not publish two APIs with the same path, as the path is used to identify the actual API. If there is already an API with path (e.g. /api/v2/abc) it is considered as the actual API and updated with the given desired API. 

If you mean something else, please let me know.

**Comment by yatamraghu** [comment]
Hi Chris,

Thanks a lot for the quick response. we are using the swagger promote tool and then in our config files  for two different API's I have given same path like 
"path": "/ab/cd/ef"
and also for the other API configuration as well I gave the same path
"path": "/ab/cd/ef"

But all the remaining properties are differently declared and as you mentioned in documentation 
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.-API-Configuration#how-the-actual-api-is-looked-upped

It is creating two API's with same path. we would like to avoid the second the API from being configured in the API Manager.

we are using Axway API Gateway 7.5.3 with SP12

Thanks
Raghu

**Comment by cwiechmann** [comment]
So, you mean, you have configured for instance a different vhost or apiRoutingKey? If that is the case, yes Swagger-Promote will create two APIs with the same path. 

But what is then reason to configure different criteria (vhost, apiRoutingKey) for each API, if you don't want them exposed that way?

**Comment by yatamraghu** [comment]
Hi Chris,

Thanks again for the proactive feedback.

we have approximately 200 API's that were exposed in our API-Manager and our customers are publishing their API's using swagger promote tool. We wanted to have a unique resource path for all the API's that were going to be configured in our API-Manager. This is the reason we wanted to know that is there a way that we can restrict two customer from creating their own API's with same front end resource path.

Also we faced issues back in time that a customer created two API's with same resource path and same swagger definition and published both of them by providing access to the same application. Then all the requests which are coming for this endpoint are failed because they pointed to the new API which was published at latest.

Thanks
Raghu

**Comment by cwiechmann** [comment]
Are your customers using an Admin- or Org-Admin-Account to register APIs? 
Would it be an option to use different V-Hosts per customer organization to avoid clashes?
What do you mean with: "_We wanted to have a unique resource path for all the API's_" ?
