### ISSUE TITLE
[Feature] Include default log4j.xml in Maven-Artifact

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apimanager-swagger-promote#250]
**User story**
Swagger-Promote ships a default log4j.xml inside the lib folder of the distribution package, which is not available, when using Swagger-Promote as a Java-Dependency. 
It would be great to include that log4j.xml file also as part of the Java-Archive.

**Comment by gwandwingor** [comment]
Hi @cwiechmann ,
When I saw this feature it made me think about an other one that would be interesting to have. It would be nice to be able to override the log level from the command line so you can replay your pipelines with a debug mode shoud they fail during deployment.

If I'm given time I might look into it.

**Comment by cwiechmann** [comment]
@gwandwingor, can you perhaps create another issue for that enhancement request you have?

**Comment by cwiechmann** [comment]
With the next release 1.6.6 the default log4j.xml is included in the Swagger-Promote Core-Jar-File.

**Comment by gwandwingor** [comment]
> @gwandwingor, can you perhaps create another issue for that enhancement request you have?

Sure, will do.
