### ISSUE TITLE
[BUG] Backend base path is not getting replaced for a Swagger 1.2 spec

### ISSUE THREAD

**Issue by shan916** [Axway-API-Management-Plus/apimanager-swagger-promote#267]
**Swagger-Promote version**
> 1.6.6-1

**API-Manager and Service-Pack Version**
I have tried with 7.5.3 SP7 and 7.7.20200331

**Expected behavior**
When you specify a `backendBasepath` in the api-config file, it should get replaced on the backend API in API Manager. I have tried specifying just the scheme and host and also with the path. If I include the path, the import fails with a 400.

**Actual behavior**
If I specify `"backendBasepath": "https://myhost.mydomain.com:8443"`, the logs show the host will be updated when actually, it is not.
If I specify `"backendBasepath": "https://myhost.mydomain.com:8443/mybasepath"`, the import fails with a 400.

**Log-Output in Debug**
I can provide logs later.

**Test case sample**
1. Use a Swagger 1.2 file and specify `"backendBasepath": "https://myhost.mydomain.com:8443"` in the api-config file.
2. Check API Manager and note that the backend did not get updated.
3. Use a Swagger 1.2 file and specify `"backendBasepath": "https://myhost.mydomain.com:8443/mybasepath"` in the api-config file.
4. Import fails and logs show a 400 Bad request from API Manager.

**Comment by cwiechmann** [comment]
@shan916, Is it possible to share your Swagger-Definition so that I can include it in my test-cases? 

BTW: For OpenAPI 3.0 support I'm planning anyway to make the implementation in that area more robust and flexible. See #265 - Also for OpenAPI 3.0 the backendBasepath is not supported.

TBH: Actually that part isn't really nice and maintainable.

**Comment by shan916** [comment]
Hi @cwiechmann. My issue is with Swagger 1.2. Please see the below Swagger file.

```
{
  "apiVersion": "1.0",
  "swaggerVersion": "1.2",
  "basePath": "https://example.com:8443/test-api",
  "resourcePath": "/blob",
  "apis": [
    {
      "path": "/blob",
      "operations": [
        {
          "method": "GET",
          "nickname": "getBlob",
          "summary": "Get a BLOB",
          "parameters": [
            {
              "name": "kSize",
              "required": true,
              "type": "string",
              "paramType": "query"
            },
            {
              "name": "waitTime",
              "required": false,
              "type": "string",
              "paramType": "query"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by cwiechmann** [comment]
Swagger-Promote 1.6.7 will support Swagger 1.2 and also Swagger 1.1

**Comment by cwiechmann** [comment]
@shan916, just release 1.6.7 which should fix this problem. Your feedback is highly appreciated.
