### ISSUE TITLE
[Help]Need information on swagger file which contains api defnition needed for this process

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#280]
**Swagger-Promote Version**
1.6.3

**API-Manager and Service-Pack Version**
7.5.3

**Question**
Need information on swagger file which contains api defnition needed for this process We want to encourage developers to create swagger for their apis. TDo you have any information that we can give them to follow standard on swagger? Like version, any links. Please suggest the swagger requirements needed to use this process.

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Swagger-Promote itself has no specific requirements to work. However, I can recommend to read here:
https://docs.axway.com/bundle/axway-open-docs/page/docs/api_mgmt_overview/api_mgmt_lifecycle/index.html

And use the Deep-Links to get more information.

**Comment by hakila** [comment]
I am asking swagger file specs which is given as input to swagger promote. 
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/3.-Swagger--or-WSDL-File
Above link did not give any specs on how to generate swagger file or swagger version etc.

**Comment by cwiechmann** [comment]
Swagger-Promote supports OpenAPI 3.0 (with version 1.6.7 in combination with API-Manager 7.7), Swagger 1.2 and 2.0.

**Comment by cwiechmann** [comment]
Added a section on the page you mentioned to make clear what is supported:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/3.-Swagger--or-WSDL-File#support-api-specifications

**Comment by hakila** [comment]
So it needs either one of those as input for -a. Not all. If i just say to developers swagger2.0 is require that should suffice as we want swagger as standard. I don't have to mention about about openapi or wsdl. Correct me if I am wrong.
Also is it possible to put some links as another column as an example ?
