### ISSUE TITLE
[BUG]In issue 213, we asked about post processing. Is that fixed?

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#281]
**Swagger-Promote version**
> Please make sure to use the latest Swagger-Promote version.
1.6.5
**API-Manager and Service-Pack Version**
7.7

**Expected behavior**

We are expecting quota, applications etc for an api to be published in Post-Processing file 
**Actual behavior**
But it is not working. When this feature going to be released? I also updated #213 but did not see the response. Please see that issue for more details. Hence opened new ticket. Please suggest.
**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
Hi @hakila, The issue #213 is closed, hence there is no additional fix for that. 

> We are expecting quota, applications etc for an api to be published in Post-Processing file
You mean you expect the applications to be configured like requested in #180 ?

To extend the post-processing file, this isn't implemented I see. I'll create a new issue for that requirement to have it really visible.

**Comment by hakila** [comment]
Please let us know approximate time when this will be fixed. Also is it possible to put application names instead of application ids in post processing file?

**Comment by cwiechmann** [comment]
@hakila, just re-reading the requirement. 

It was never planned to expose complex information (such as quotas) in that post processing file. You can use that ID to trigger the API-Manager REST-API to gather required information to implement your custom post-processing.
