### ISSUE TITLE
[BUG] Cannot set Oauth authentication Profile using its name

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apimanager-swagger-promote#288]
**Swagger-Promote version**
> Please make sure to use the latest Swagger-Promote version.
1.6.7-1

**API-Manager and Service-Pack Version**
7.5.3 SP12

**Expected behavior**
Documentation says Oauth type outbound authentication profiles can be created using their names 

[https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.2-Configure-API-Outbound-Authentication#oauth](url)

```
         "parameters":{
            "providerProfile":"<Name-of-configured-OAuth-Profile>",
            "ownerId":"${authentication.subject.id}"
         },
         "type":"oauth"
```

Outbound authentication profiles should be configured the same way as Request/Routing/Response policies, using their names instead of their complete EntityStore reference.

**Actual behavior**
Only EntityStore type references to profile such as below are accepted by Swagger Promote.
```
  "authenticationProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "parameters" : {
      "providerProfile" : "<key type='AuthProfilesGroup'><id field='name' value='Auth Profiles'/><key type='OAuthGroup'><id field='name' value='OAuth2'/><key type='OAuthProviderProfile'><id field='name' value='Google'/><key type='OAuthAppProfile'><id field='name' value='Test Credentials'/></key></key></key></key>",
      "ownerId" : "${authentication.subject.id}"
    },
    "type" : "oauth"
  } ],
```

When only profile name is provided, outbound authentication profile is created but link to profile is empty

![image](https://user-images.githubusercontent.com/22820414/84171820-89ee0c00-aa7b-11ea-9089-89f9be5f72d6.png)

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

1. Create Oauth2 Client credentials named "Test Credentials" in Policy studio and make them available to API Manager sections of the Server Settings.
2. Create an API configuration using following JSON sample
```
 "authenticationProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "parameters" : {
      "providerProfile" : "Test Credentials",
      "ownerId" : "${authentication.subject.id}"
    },
    "type" : "oauth"
  } ], 
```
3. Deploy API
4. Check imported Frontend API in API Manager

**Comment by cwiechmann** [comment]
Hi @gwandwingor, I can confirm that issue. Thanks for reporting!

I have mirrored the issue to the APIM-CLI project, which will replace Swagger-Promote very soon. Can you find your issue here: https://github.com/Axway-API-Management-Plus/apim-cli/issues/2

I see, you are still using API-Manager 7.5.3, which will not be supported by the APIM-CLI anymore. Can you please let me know, the importance to have a fix in Swagger-Promote as 7.5.3 becomes EOS very soon anyway?

**Comment by gwandwingor** [comment]
Hi @cwiechmann ,

The issue was brought to our attention by a partner that uses the wiki page to create its config files on his own.

I confirm that we are aware of the 7.5.3 EOF in october and are already in the process of migrating to 7.7.0.202005, which will give us the opportunity to switch to the new apim-cli tool.
But given our current velocity, I hardly see us being ready to complete the upgrade before the end of july. Until then, we will still rely on the current apimanager-swagger-promote.

So if that's possible and doesn't require too much work, we'd like to have the fix you made on the apim-cli repo also backported here too.

**Comment by cwiechmann** [comment]
@gwandwingor, the new CLI is heavily refactored esp. in that area, so that the fix cannot just be back-ported. Therefore I'm willing to close this issue now as you can use for now as a workaround the fully internal FED-Store path.
I hope that is okay for.

**Comment by gwandwingor** [comment]
Thanks,
I'm closing the issue then.
