### ISSUE TITLE
API export issue

### ISSUE THREAD

**Issue by shahtejasa** [Axway-API-Management-Plus/apimanager-swagger-promote#295]
This api is swagger 1.1

C:\Axway\swagger-promote-1.6.7-1\scripts>api-export.bat -a /wbttsmadmin -s dev -l ..\apis ------------------------------------------------------------------------ API-Manager Promote: 1.6.7-1 - E X P O R T
To report issues or get help, please visit: https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote ------------------------------------------------------------------------
0      INFO  nvironmentProperties| Trying to load environment properties from file: env.properties ... not found. 0      INFO  nvironmentProperties| Loaded environment properties from file: env.dev.properties 985    INFO     APIManagerAdapter| API-Manager version is: 7.7.20200930 985    INFO               Proxies| Sending request to find existing APIs: https://hostname:443/api/portal/v1.3/proxies?field=path&op=eq&value=%2Fwbttsmadmin 1360   INFO               Proxies| Found existing API on path: '/wbttsmadmin' (unpublished) (ID: 'b5870476-8d45-44a6-8a41-91aa7456090b') 1360   INFO               Proxies| Found: 1 exposed API(s) java.lang.StringIndexOutOfBoundsException: String index out of range: 100         at java.lang.String.checkBounds(String.java:385)         at java.lang.String.<init>(String.java:545)         at com.axway.apim.api.definition.WSDLSpecification.configure(WSDLSpecification.java:37)         at com.axway.apim.api.definition.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:41)         at com.axway.apim.adapter.APIManagerAdapter.getOriginalAPIDefinitionFromAPIM(APIManagerAdapter.java:725)         at com.axway.apim.adapter.APIManagerAdapter.getAPIManagerAPI(APIManagerAdapter.java:333)         at com.axway.apim.api.export.APIExportConfigAdapter.getExportAPI(APIExportConfigAdapter.java:124)         at com.axway.apim.api.export.APIExportConfigAdapter.getAPIsToExport(APIExportConfigAdapter.java:90)         at com.axway.apim.api.export.APIExportConfigAdapter.exportAPIs(APIExportConfigAdapter.java:72)         at com.axway.apim.ExportApp.run(ExportApp.java:138)         at com.axway.apim.ExportApp.main(ExportApp.java:36) 1735   ERROR            ExportApp| Can't initialize API-Manager API-State. com.axway.apim.lib.errorHandling.AppException: Can't initialize API-Manager API-State.         at com.axway.apim.adapter.APIManagerAdapter.getAPIManagerAPI(APIManagerAdapter.java:358)         at com.axway.apim.api.export.APIExportConfigAdapter.getExportAPI(APIExportConfigAdapter.java:124)         at com.axway.apim.api.export.APIExportConfigAdapter.getAPIsToExport(APIExportConfigAdapter.java:90)         at com.axway.apim.api.export.APIExportConfigAdapter.exportAPIs(APIExportConfigAdapter.java:72)         at com.axway.apim.ExportApp.run(ExportApp.java:138)         at com.axway.apim.ExportApp.main(ExportApp.java:36) Caused by: com.axway.apim.lib.errorHandling.AppException: Can't read Swagger-File.         at com.axway.apim.adapter.APIManagerAdapter.getOriginalAPIDefinitionFromAPIM(APIManagerAdapter.java:728)         at com.axway.apim.adapter.APIManagerAdapter.getAPIManagerAPI(APIManagerAdapter.java:333)         ... 5 more Caused by: com.axway.apim.lib.errorHandling.AppException: Can't handle API specification. No suiteable specification implementation found.         at com.axway.apim.api.definition.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:50)         at com.axway.apim.adapter.APIManagerAdapter.getOriginalAPIDefinitionFromAPIM(APIManagerAdapter.java:725)         ... 6 more
C:\Axway\swagger-promote-1.6.7-1\scripts>

**Comment by cwiechmann** [comment]
Hi @shahtejasa, Thanks for reporting this issue. However, Swagger-Promote has been replaced by the APIM-CLI a year ago.
Please try to export your API(s) with the CLI and if you encounter a problem please open an issue the APIM-CLI-Project.
https://github.com/Axway-API-Management-Plus/apim-cli
