### ISSUE TITLE
Trust all API Manager certificates

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apimanager-swagger-promote#31]
When API Manager's "API Portal" listener SSL certificate is issued by a self-signed certificate, we get a `com.axway.apim.lib.AppException: Can't login to API-Manager` 
caused by a 
`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
My guess is this has something to do with the Apache http client settings, more precisely the `TrustSelfSignedStrategy`. 
Unless it is expected to be implemented like that, maybe a `TrustAllStrategy` would work better.

**Comment by cwiechmann** [comment]
@gwandwingor, thanks for letting me know. Have just changed it to your recommendation. Will be part of the next release.

**Comment by cwiechmann** [comment]
Fixed with version 1.4.2
