### ISSUE TITLE
Relative API-Image path wasn't working as expected

### ISSUE THREAD

**Issue by cbrowet-axway** [Axway-API-Management-Plus/apimanager-swagger-promote#52]
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/blob/65314ae4f1a3ea4fc44ebd3cd5a4523ff8fbb205/src/main/java/com/axway/apim/swagger/APIImportConfigAdapter.java#L589

If, e.g, `scripts/run-swagger-import.sh -a CalculatorREST.json -c CalculatorRest-promote.json ...` is executed, an image cannot be found as `/samples/images/sample-api-icon.jpg` is tried.

Workaround:
Use `scripts/run-swagger-import.sh -a CalculatorREST.json -c ./CalculatorRest-promote.json ...`

**Comment by cwiechmann** [comment]
Has been released with version 1.5.2.
