### ISSUE TITLE
API Manager: run-swagger-import.sh not working properly with orgs and apps

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#56]
I used the swagger script and created api with couple of orgs and apps using config file. After that I added api to one more org and app. I ran the script again with same config file and I got below error
2708   INFO     APIManagerAdapter| All desired organizations: [ATP_ATP_Org, X91_91_Org, API Development] have already access. Nothing to do.
2708   INFO     APIManagerAdapter| Removing access for orgs: [ATP_CUS_Org] from API: STST Minimum Stay (Category 06) Rules
2849   INFO     APIManagerAdapter| Removed permission from organization: 'ATP_CUS_Org'
2850   INFO     APIManagerAdapter| All desired applications: [[ATP_ATP_Apps], [X91_91_App]] have already a subscription. Nothing to do.
2850   INFO     APIManagerAdapter| Removing access for appplications: [[ATP_CUS_App]] from API: STST Minimum Stay (Category 06) Rules
2850   DEBUG    APIManagerAdapter| Removing API-Access for application 'ATP_CUS_App'
2897   ERROR    APIManagerAdapter| Received status code: 404
2898   ERROR    APIManagerAdapter| Received response: {"errors":[{"code":102,"message":"The entity could not be found.  Please refresh your session."}]}
2898   ERROR          RestAPICall| Response: 'HTTP/1.1 404 Not Found'
2898   ERROR    APIManagerAdapter| Can't delete API access requests for application.
2899   ERROR                  App| Can't delete API access requests for application.
com.axway.apim.lib.AppException: Can't delete API access requests for application.
        at com.axway.apim.actions.tasks.ManageClientApps.removeAppSubscrioption(ManageClientApps.java:114)
        at com.axway.apim.actions.tasks.ManageClientApps.execute(ManageClientApps.java:65)
        at com.axway.apim.actions.UpdateExistingAPI.execute(UpdateExistingAPI.java:55)
        at com.axway.apim.swagger.APIManagerAdapter.applyChanges(APIManagerAdapter.java:153)
        at com.axway.apim.App.run(App.java:160)
        at com.axway.apim.App.main(App.java:42)
Caused by: com.axway.apim.lib.AppException: Unable to parse HTTP-Response
        at com.axway.apim.actions.rest.RestAPICall.parseResponse(RestAPICall.java:73)
        at com.axway.apim.actions.rest.DELRequest.execute(DELRequest.java:27)
        at com.axway.apim.actions.tasks.ManageClientApps.removeAppSubscrioption(ManageClientApps.java:111)
        ... 5 more
Caused by: com.axway.apim.lib.AppException: Failure creating/deleting API-Access to/from application: '[ATP_CUS_App]'. Mode: 'MODE_REMOVE_API_ACCESS'
        at com.axway.apim.actions.tasks.ManageClientApps.parseResponse(ManageClientApps.java:138)
        at com.axway.apim.actions.rest.RestAPICall.parseResponse(RestAPICall.java:65)
        ... 7 more
In my config file, I have these orgs ATP_ATP_Org, X91_91_Org, API Development and [ATP_ATP_Apps], [X91_91_App] apps. From ui i added api to ATP_CUS_Org and ATP_CUS_App. 
I ran the script again with same config file but got above error. But when I checked, it removed access to ATP_CUS_Org and ATP_CUS_App as they are not config file. Everything worked as expected but exception made me think something is not right.

**Comment by cwiechmann** [comment]
@hakila, Thanks for the feedback. I got similar feedback from another user and already made some improvements for the application-handling. Perhaps it's already fixed. 
To verify this, would it be possible to share the complete config-file here (wipe out everything confidential)? And just let me know, the exact steps needed to replicate the issue.
And let me know the API-Manager Version your are using.

Thanks!
Chris

**Comment by hakila** [comment]
Ran the script and then through ui add one org and one app. Come back and run the script again.
[apitest_axway.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3203247/apitest_axway.zip)

**Comment by cwiechmann** [comment]
I thinking about to release next week. Feel free to test with the attached pre-release based on 1.5.1 including all latest changes:
[apimanager-swagger-promote-1.6-SNAPSHOT-1.5.1.tar.gz](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3204699/apimanager-swagger-promote-1.6-SNAPSHOT-1.5.1.tar.gz)
I'm happy to get your feedback.

**Comment by hakila** [comment]
I tested snapshot version this scenario. It is working fine. Thanks for the quick turnover.

**Comment by cwiechmann** [comment]
That's perfect! Thanks for letting me know. Closing this issue now.
