### ISSUE TITLE
quota not being applied

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#57]
I see https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.3-Configure-API-Quotas
application quota are not supported. Is that still true? But application default and system quota is supported. But they are not working for me. I put below in config file
   "applicationQuota":{
      "id": "00000000-0000-0000-0000-000000000001",
      "restrictions":[
         {
            "api":"12b13720-b0d7-4f22-aee2-ad2b7ffaa1a3",
            "method":"*",
            "type":"throttlemb",
            "config":{
               "period":"hour",
               "mb":50,
               "per":1
            }
         }
      ]
   }
But it did not get applied. In the link, it was not mentioned to give id and api in the json. But script log shows this
2686   INFO        APIChangeState| Changed property: applicationQuota[Desired: 'APIQuota [id=null, type=APPLICATION, restrictions=[QuotaRestriction [api=null, method=*, type=throttlemb, config={period=hour, mb=50, per=1}]]]' vs Actual: 'null']
After seeing that, I added id and api to config file, but still my application default not being applied
Below is the console output after i ran script,
2666   INFO        APIChangeState| Changed property: applicationQuota[Desired: 'APIQuota [id=00000000-0000-0000-0000-000000000001, type=APPLICATION, restrictions=[QuotaRestriction [api=12b13720-b0d7-4f22-aee2-ad2b7ffaa1a3, method=*, type=throttlemb, config={period=hour, mb=50, per=1}]]]' vs Actual: 'null']

How I do know api id on the fly to configure in quota. Could you please explain how this quota works in script.

**Comment by cwiechmann** [comment]
Hi @hakila, you discovered a known bug (See here: #55), which will be fixed in the next version. For now, please configure alway both: System- & Application-Quota to get it applied. Hope this works for your!

**Comment by hakila** [comment]
Hi Chris,
I tested quota with new snapshot jar. Initially I had both app default and system quota defined. Now I removed system quota and chnaged the messages number for app default. It got applied but system quota still existed. I expect system quota to be deleted as config file contains all the info needed for api.
Same is happening for app default removed in config file and chnaged the system quota parameter. Change is applied but default app quota is still there.
For appa and orgs, it is behaving different. whatever is mentioned in config file those only gets applied and rest will be deleted but same is not observed in case of quota
 Also, when is the approximate timeline for app level ( not default) quota available

**Comment by cwiechmann** [comment]
Hi @hakila, your observation is correct. Today the tool ignores all properties that are not given in the config-file. This has something to do with performance, as otherwise really everything must be loaded from the API-Manager to get the actual state, which would lead to even more REST-API-Calls. 

I'm thinking about a NOT_SET flag. This would give you a way to really enforce a property to be cleared, but this hasn't the highest prio.

**Comment by hakila** [comment]
At this time, what has to go in config file? How can we keep track of what has to be deleted if script does not handle it. This is kind of important to us.
Tags,Orgs, Applications, markdown loc etc they all are taken from config file and if they are not mentioned they get deleted if existed previously? Is this correct?
It does not work the same way for quotas? Are there any other elements fall in this scenario?

**Comment by hakila** [comment]
Could you please give update on this? Also when can we get app specific quota feature? Please give approximate timeframe

**Comment by cwiechmann** [comment]
It is all taken from the configuration file, but it must be declared otherwise it is skipped.  

Supposing you have an API with 5 tags in your API-Manager and want to remove all of them. Just completely remove the Tags-Section from the configuration-file will not work, as the tool will then skip the tag-handling, because you haven’t declared anything.  

For tags, you could do it like this:
“tags”: {}
And this means: I don’t want any tags!

**Comment by cwiechmann** [comment]
The app specific quota feature isn’t planned right now.
This tool handles APIs and not app. And I don’t want to mix & match everything, because it would become unmanageable.

Perhaps a second module for apps following the same principle.
