### ISSUE TITLE
Basic questions on the swagger promote script

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#59]
I was testing swagger script with different scenarios
1) I have api say API1 that was existed. But that has null version. I used swagger promote script which created same api with  version mentioned in config file. Both APIs have same name and same path. Later I could not reproduce this scenario. During which instances, script creates api of same name and path? I understand from console logs that it either updates existing api if math is found or if it is deep change, it deletes and creates api. Wondering is there any scenarios it creates new api leaving the old api sitting there.
2)If I have two apis with same names and information and if we run swagger script, which api script will pick as we have two apis already? based on what it makes the decisions?
3) How versioning numbers are given? If I dont give version number, it always puts 1.0 . when will I see other version numbers.
4) If I want to do some post processing after I run the script, what are the ways. It would be nice if script return api id. Let me explain my scenario:
I create config file on the fly based on input parameters. If I want to update description markdown file path, I can do in config file at api level. But at the method description markdown file can be given after the api is created. I can use rest call to do. But how do i know the apiId that swagger script created? I can query based on api name using rest call but I am not comfortable as there may be multiple apis with same names .

**Comment by cwiechmann** [comment]
Hi @hakila, let me quickly answer your questions:

1. The only information used to identify an existing API is based on the exposure path. If you have two APIs exposed at the same time with the same path, I'm not sure what happens right now, but I guess it's the first returned by the REST-API. Swagger-Promote will always clean up existing APIs, as you basically have 1 API declared as desired and this should be reflected as this ONE and ONLY API in API-Manager. 
2. The version number in API-Manager is just a meta information and basically has no impact in terms of Lifecycle. If you don't provide the version number in the config file and you see version 1.0, I assume API-Manager fills in by default 1.0. Swagger-Promote has no default handling implemented for the version number.
3. That's a valid use-case and I'll create a dedicated issue for that enhancement request to keep track of it. I have to think about it how to export the generated API-ID. I think it must be flexible enough to also export other information of the actual API.

**Comment by cwiechmann** [comment]
@hakila, I have created the issue #60 to support export of API-Details
