### ISSUE TITLE
Maven repo

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apimanager-swagger-promote#64]
Do you have in mind to distribute this tool in central maven repositories?

**Comment by cwiechmann** [comment]
Hello @gcornacchia, Yes, I get this request from time to time from customers and someday I (or someone else) will implement this.
Whoever is experienced developing Maven-Plugins, feel free to take this and contribute.

**Comment by druppelt** [comment]
@cwiechmann I think this should be 2 maven artifacts. Your code as some kind of swagger-promote-core and a maven plugin. The maven plugin may be maintained by the community, but the core should definitely be maintained by you or your company.

**Comment by gcornacchia** [comment]
Yeah I totally agree with @druppelt

**Comment by cwiechmann** [comment]
A customer has already created a working Maven-Plugin and shared it with me. I need to identify the best way to incorporate it into the project in order to have it maintainable & auto-testable.

**Comment by cwiechmann** [comment]
Starting from version 1.5.3 Swagger-Promote will be available on Maven Central. 
```
<dependency>
  <groupId>com.github.axway-api-management-plus.swagger-promote</groupId>
  <artifactId>axway-swagger-promote-core</artifactId>
  <version>1.5.3</version>
</dependency>
```
A Default-Maven plugin will follow in one of the next releases.
