### ISSUE TITLE
[Feature] add http proxy support Feature-httpProxySuppor

### ISSUE THREAD

**Issue by kervoaz** [Axway-API-Management-Plus/apimanager-swagger-promote#68]
Hello,

I don't find a simple way to use an http proxy to connect to the manager.
Our apimanager is hosted on aws and we need setup a proxy to reach the server.
-->
I create the branch Feature-httpProxySuppor in order to support http proxy.
With this change we can pass proxy setup to the jvm -Dhttp[s].proxyPort=xx -Dhttp[s].proxyHost=yy

regards

**Comment by cwiechmann** [comment]
Released with version 1.5.3
