### ISSUE TITLE
"productVersion":"7.5.3" Error getting app info. what is apiroutingkey?

### ISSUE THREAD

**Issue by kervoaz** [Axway-API-Management-Plus/apimanager-swagger-promote#71]
hello

I receive the following error:
12522  ERROR er.APIManagerAdapter| Error AppInfo from API-Manager. Can't parse response: {"registrationEnabled":true,"minimumPasswordLength":6,"baseOAuth":false,"resetPasswordEnabled":true,..."productVersion":"7.5.3"....}

it seems that the nullpointer exception comes from `getApiManagerConfig(String configField) ` for configField = "apiRoutingKeyEnabled" when extracting this field from json config response.

what is the  goal of this param? is it possible to bypass?

thnaks

**Comment by cwiechmann** [comment]
@kervoaz, damn. No you can't bypass this and I haven't realized this, as the Fully-Automated tests are running with 7.6.2 and 7.7 only. I'll create a bugfix release for that.
FYI: apiRoutingKeyEnabled is an option in API-Manager 7.6.2 allowing you to route traffic based on a version query parameter.

**Comment by cwiechmann** [comment]
@kervoaz, could you please validate again on your 7.5.3 using 1.5.2-1! I didn't had the chance to test it, but I think it should work.

**Comment by kervoaz** [comment]
Thank you Chris.
I will test on monday after this long we :)
reagrds
Christophe
