### ISSUE TITLE
How to mention method level markdown url in config file

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#76]
Is there a way that I can put method level markdown url in config file so that when api got created, it will get the markdown location for methods. For API level, I am able to do it but don't know how to configure for method level. Please suggest

**Comment by cwiechmann** [comment]
Anything on Method-Level currently not supported. This includes documentation, policies, etc. The code and the structure of the config file is prepared to support it in the future, but it requires a considerable amount of time to implement it.

**Comment by hakila** [comment]
Thanks for the update.
