### ISSUE TITLE
Is there a way to encrypt password in env.properties 

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#77]
We have security requirement not to expose passwords in plain text. Currently env.properties , we need to mention it as plain text. Is there a way to put as encrypted and your script will decrypt and connect to respective apimanager/gateway.

**Comment by cwiechmann** [comment]
I was thinking about it, but it's difficult to implement as the code is open source and everything I implement to decrypt the password could be revealed from the source-code and used to decode the password manually. So it would be useless. 
The idea of having that option to store the required password in an env-file, was to make it read-only to a specific user only. And this user is executing Swagger-Promote.

I'm open for other ideas to make it better, just let me know.

**Comment by hakila** [comment]
since script takes passwrd as argument, i will implement on my side but script will still use env.properties for other parameters correct?

**Comment by cwiechmann** [comment]
Yes, correct. It's merging the parameters as described here:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/5.-Environment-property-files
