### ISSUE TITLE
URL for Swagger-Definitions

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apimanager-swagger-promote#9]
In the current version the tool only supports locally stored Swagger-Files, but it makes sense to get the Swagger-Definition from a URI as it's support by the API-Manager anyway. Hence it should be a quick win.

Thanks @rathnapandi collecting this feedback.

**Comment by rchinthakuntla** [comment]
+1

**Comment by cwiechmann** [comment]
Hi @rchinthakuntla, @rathnapandi, I'm planning to implement this feature now. 

Even if the API-Manager supports the direct import of Swagger-Files from a URL, the tool must pull the Swagger-File locally, to be able to compare it with the actual API.

I plan the following:
Additionally to declare the Swagger-File by: -a <path_to_local_swagger_file>, users can reference a Swagger-File by:
- providing a file: -a my_swagger.url
The key will be the file-extention ".url" and in that case the following content is expected:
user/password@https://any.host.com/path/xyz/swagger.json
With that an API-Service-Provider still has the option to programmatically reference a Remote-Swagger-File, still triggering a CI/CD-Flow. The triggered CI/CD-System, running Swagger-Promote, will have to pull down the Swagger-File and needs access to that endpoint.

- providing a URL directly: -a user/password@https://any.host.com/path/xyz/swagger.json
This is useful when the tool is started interactively just by providing the right URL.

Both option will optionally support HTTP-Basic AuthN.

Any thoughts on this? Would that work?

**Comment by cwiechmann** [comment]
Added support for it with version 1.4.0.
