### ISSUE TITLE
Support environment variables to be used in API-Config file

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#90]
I put /opt/axway/gateway-7.7/apigateway/groups/group-2/instance-1/conf/envSettings.props
env.APIIMAGES=/opt/axway/apiimages

In the config file (input to swagger promote), I used 
        "image": "${env.APIIMAGES}/Ticket.png"
 But swagger promote script is throwing error
Running API-Manager Promote version 1.5.2-1 ...
0      INFO                   App| ------------------------------------------------------------------------
0      INFO                   App| API-Manager Promote Version: 1.5.2-1
0      INFO                   App|
0      INFO                   App| To report issues or get help, please visit:
0      INFO                   App| https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
0      INFO                   App| ------------------------------------------------------------------------
9      INFO  nvironmentProperties| Loaded environment properties from file: env.properties.
816    INFO     APIManagerAdapter| API-Manager version is: 7.7.0
940    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/axway/pythonscripts/conf/apicreatejson/TESTMinimumStayCategory06Rules_transformed.json' (relative path)
942    ERROR                  App| Image not found in filesystem ('/opt/axway/pythonscripts/conf/apiconfigjson/${env.APIIMAGES}/Ticket.png') or Classpath.
com.axway.apim.lib.AppException: Image not found in filesystem ('/opt/axway/pythonscripts/conf/apiconfigjson/${env.APIIMAGES}/Ticket.png') or Classpath.
        at com.axway.apim.swagger.APIImportConfigAdapter.addImageContent(APIImportConfigAdapter.java:622)
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:148)
        at com.axway.apim.App.run(App.java:157)
        at com.axway.apim.App.main(App.java:42)
retCode from swagger script: 0

This is due to value mentioned in envSettings.props not available to swagger promote. Is there a wat swagger promote can use envSettings.props file key value?

**Comment by hakila** [comment]
Also if we have other custom env properties, how can I enforce script to use? Can you also give an example on how it can be used?

**Comment by hakila** [comment]
For example config input file to the swagger script we have oauth 
                                                "authCodeGrantTypeRequestEndpointUrl": "https://apitest.ddd.org/api/oauth/authorize",
                                              
I want to use environment variable instead of hardcoding. Please suggest how it can be done.

**Comment by cwiechmann** [comment]
Hi @hakila, the API-Gateway environment variables aren't used at all by Swagger-Promote and to my opinion they even can't, as the API-Manager REST-API doesn't expose them. They are stored on the API-Gateway instances, which might be a totally different machine than the machine running Swagger-Promote.

The only way is to use Swagger-Promote environment variables as explained here:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/5.-Environment-property-files

**Comment by cwiechmann** [comment]
Concerning the following use-case: 

```"authCodeGrantTypeRequestEndpointUrl": "https://apitest.ddd.org/api/oauth/authorize"```

This is something I do see in the env.your-stage.properties, but it's not supported at the moment. In the future, it should be possible to declare that kind of defaults.

**Comment by hakila** [comment]
I did see that link but those are predefined and swagger promote script will take them automatically. But I am looking for some custom ones and how to refer them in shell/python script before actual swagger promote script is being invoked. So you are telling this feature will come in future?

**Comment by cwiechmann** [comment]
Yes, I think this requirement makes sense and it's very likely to be added in a future release.

**Comment by cwiechmann** [comment]
Delivered with version 1.6.0
